import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:server_box/core/service/geo_bundle.dart';

/// The published format, read against the vectors the other repository writes.
///
/// `test/fixtures/geo/bundle_ip{4,6}_v1.{bin,json}` are checked into both
/// repositories and generated by neither reader. A reader tested only against
/// bytes its own writer produced agrees with itself and proves nothing — and
/// every way this format goes wrong is silent, because a record read at the
/// wrong offset is a coordinate somewhere plausible rather than an error.
void main() {
  late Directory tmp;

  setUp(() async => tmp = await Directory.systemTemp.createTemp('geo-bundle-'));
  tearDown(() => tmp.delete(recursive: true));

  Future<String> place(List<int> bytes, [String name = 'b.bin']) async {
    final path = '${tmp.path}${Platform.pathSeparator}$name';
    await File(path).writeAsBytes(bytes);
    return path;
  }

  Future<List<int>> vector(String name) =>
      File('test/fixtures/geo/$name').readAsBytes();

  group('the shared vectors', () {
    for (final name in ['bundle_ip4_v1', 'bundle_ip6_v1']) {
      test('$name reads back exactly what it says it should', () async {
        final bundle = GeoBundle.open(await place(await vector('$name.bin')));
        addTearDown(() => bundle?.close());
        expect(bundle, isNotNull, reason: 'the vector must parse');

        final expected =
            jsonDecode(
                  await File('test/fixtures/geo/$name.json').readAsString(),
                )
                as Map<String, dynamic>;
        expect(bundle!.family, expected['family']);
        expect(bundle.count, expected['records']);
        expect(bundle.year, 2026);
        expect(bundle.month, 9);

        (expected['lookups'] as Map<String, dynamic>).forEach((address, want) {
          final got = bundle.lookup(InternetAddress(address));
          if (want == null || want == 'gap') {
            // A gap and an empty bucket are one answer here on purpose: the
            // caller does the same for both, and telling them apart would be
            // a distinction nothing acts on.
            expect(got, isNull, reason: address);
            return;
          }
          final coords = (want as List).cast<num>();
          expect(got, isNotNull, reason: address);
          // The quantum is 90/32767 of latitude, about 0.003 degrees —
          // tighter than that would be testing rounding.
          expect(
            got!.lat,
            closeTo(coords[0].toDouble(), 0.005),
            reason: address,
          );
          expect(got.lon, closeTo(coords[1].toDouble(), 0.01), reason: address);
        });
      });
    }
  });

  group('a file that is not one', () {
    test('a missing path is null, not a throw', () async {
      expect(GeoBundle.open('${tmp.path}/nope.bin'), isNull);
    });

    test('an empty file', () async {
      expect(GeoBundle.open(await place(const [])), isNull);
    });

    test('the wrong magic', () async {
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      bytes[0] = 0x00;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });

    test('a format this build does not read', () async {
      // A newer file would parse field by field and mean something else. The
      // stride is the whole risk: read wrongly it answers rather than fails.
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      bytes[4] = 2;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });

    test('a family this build does not know', () async {
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      bytes[5] = 5;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });

    test('an impossible build month', () async {
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      bytes[8] = 13;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });

    test('a truncated download', () async {
      // What a connection dropping mid-file leaves. The header still parses
      // and describes more records than are there, so the length is checked.
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      expect(
        GeoBundle.open(await place(bytes.sublist(0, bytes.length - 3))),
        isNull,
      );
    });

    test('a bucket table that does not close at the record count', () async {
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      // The last table entry, which every lookup in the last bucket indexes
      // with. Wrong, it reads past the end of the file.
      final last = 16 + 256 * 4;
      bytes[last + 3] = 0xFF;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });

    test('a bucket entry outside the record table', () async {
      final bytes = (await vector('bundle_ip4_v1.bin')).toList();
      // The vector has four records. An intermediate entry past that count
      // would make a lookup seek beyond the file even though the final table
      // entry still looks correct.
      bytes[16 + 4 + 3] = 5;
      expect(GeoBundle.open(await place(bytes)), isNull);
    });
  });

  group('what a lookup answers', () {
    test('the wrong family is null rather than a wrong coordinate', () async {
      // The v4 file read with a v6 address would otherwise take the leading
      // four bytes of the address as a key and answer with somewhere real.
      final bundle = GeoBundle.open(
        await place(await vector('bundle_ip4_v1.bin')),
      );
      addTearDown(() => bundle?.close());
      expect(bundle!.covers(InternetAddress('8.8.8.8')), isTrue);
      expect(bundle.covers(InternetAddress('2620:fe::fe')), isFalse);
      expect(bundle.lookup(InternetAddress('2620:fe::fe')), isNull);
    });

    test('two addresses in one /48 are one answer', () async {
      // The key is 48 bits, so that is the finest distinction the file makes.
      final bundle = GeoBundle.open(
        await place(await vector('bundle_ip6_v1.bin')),
      );
      addTearDown(() => bundle?.close());
      final a = bundle!.lookup(InternetAddress('2620:fe::fe'));
      final b = bundle.lookup(InternetAddress('2620:fe::1:2:3'));
      expect(a, isNotNull);
      expect(b, a);
    });

    test('every record in the vector is reachable', () async {
      // Walks the file rather than sampling it: a stride that is off by one
      // reads plausibly for a while and wrongly further in.
      final bundle = GeoBundle.open(
        await place(await vector('bundle_ip4_v1.bin')),
      );
      addTearDown(() => bundle?.close());
      expect(bundle!.count, 4);
      expect(bundle.lookup(InternetAddress('8.0.0.0')), isNotNull);
      expect(bundle.lookup(InternetAddress('8.8.8.8')), isNotNull);
      expect(bundle.lookup(InternetAddress('8.9.0.0')), isNull, reason: 'gap');
      expect(bundle.lookup(InternetAddress('10.0.0.1')), isNotNull);
    });
  });
}
