import 'package:flutter/material.dart';

/// Supported, non-deprecated Material color roles.
abstract final class ThemePalette {
  static const roles = {
    'primary',
    'onPrimary',
    'primaryContainer',
    'onPrimaryContainer',
    'primaryFixed',
    'primaryFixedDim',
    'onPrimaryFixed',
    'onPrimaryFixedVariant',
    'secondary',
    'onSecondary',
    'secondaryContainer',
    'onSecondaryContainer',
    'secondaryFixed',
    'secondaryFixedDim',
    'onSecondaryFixed',
    'onSecondaryFixedVariant',
    'tertiary',
    'onTertiary',
    'tertiaryContainer',
    'onTertiaryContainer',
    'tertiaryFixed',
    'tertiaryFixedDim',
    'onTertiaryFixed',
    'onTertiaryFixedVariant',
    'error',
    'onError',
    'errorContainer',
    'onErrorContainer',
    'surface',
    'onSurface',
    'surfaceDim',
    'surfaceBright',
    'surfaceContainerLowest',
    'surfaceContainerLow',
    'surfaceContainer',
    'surfaceContainerHigh',
    'surfaceContainerHighest',
    'onSurfaceVariant',
    'outline',
    'outlineVariant',
    'shadow',
    'scrim',
    'inverseSurface',
    'onInverseSurface',
    'inversePrimary',
    'surfaceTint',
  };

  /// A color as a manifest writes one: an ARGB integer, or the name of a role
  /// resolved against [scheme]. `null` for anything else, which every caller
  /// treats as "not configured" — the values are validated at install time, so
  /// this is the second reading of the same rules rather than the only one.
  static Color? spec(Object? value, ColorScheme scheme) => switch (value) {
    final int value => Color(value),
    final String role => resolve(scheme, role),
    _ => null,
  };

  static Color resolve(ColorScheme scheme, String role) => switch (role) {
    'primary' => scheme.primary,
    'onPrimary' => scheme.onPrimary,
    'primaryContainer' => scheme.primaryContainer,
    'onPrimaryContainer' => scheme.onPrimaryContainer,
    'primaryFixed' => scheme.primaryFixed,
    'primaryFixedDim' => scheme.primaryFixedDim,
    'onPrimaryFixed' => scheme.onPrimaryFixed,
    'onPrimaryFixedVariant' => scheme.onPrimaryFixedVariant,
    'secondary' => scheme.secondary,
    'onSecondary' => scheme.onSecondary,
    'secondaryContainer' => scheme.secondaryContainer,
    'onSecondaryContainer' => scheme.onSecondaryContainer,
    'secondaryFixed' => scheme.secondaryFixed,
    'secondaryFixedDim' => scheme.secondaryFixedDim,
    'onSecondaryFixed' => scheme.onSecondaryFixed,
    'onSecondaryFixedVariant' => scheme.onSecondaryFixedVariant,
    'tertiary' => scheme.tertiary,
    'onTertiary' => scheme.onTertiary,
    'tertiaryContainer' => scheme.tertiaryContainer,
    'onTertiaryContainer' => scheme.onTertiaryContainer,
    'tertiaryFixed' => scheme.tertiaryFixed,
    'tertiaryFixedDim' => scheme.tertiaryFixedDim,
    'onTertiaryFixed' => scheme.onTertiaryFixed,
    'onTertiaryFixedVariant' => scheme.onTertiaryFixedVariant,
    'error' => scheme.error,
    'onError' => scheme.onError,
    'errorContainer' => scheme.errorContainer,
    'onErrorContainer' => scheme.onErrorContainer,
    'surface' => scheme.surface,
    'onSurface' => scheme.onSurface,
    'surfaceDim' => scheme.surfaceDim,
    'surfaceBright' => scheme.surfaceBright,
    'surfaceContainerLowest' => scheme.surfaceContainerLowest,
    'surfaceContainerLow' => scheme.surfaceContainerLow,
    'surfaceContainer' => scheme.surfaceContainer,
    'surfaceContainerHigh' => scheme.surfaceContainerHigh,
    'surfaceContainerHighest' => scheme.surfaceContainerHighest,
    'onSurfaceVariant' => scheme.onSurfaceVariant,
    'outline' => scheme.outline,
    'outlineVariant' => scheme.outlineVariant,
    'shadow' => scheme.shadow,
    'scrim' => scheme.scrim,
    'inverseSurface' => scheme.inverseSurface,
    'onInverseSurface' => scheme.onInverseSurface,
    'inversePrimary' => scheme.inversePrimary,
    'surfaceTint' => scheme.surfaceTint,
    _ => throw FormatException('Unknown color role: $role'),
  };

  static ColorScheme apply(ColorScheme base, Map<String, int> palette) {
    Color? role(String key) =>
        palette[key] == null ? null : Color(palette[key]!);
    return base.copyWith(
      primary: role('primary'),
      onPrimary: role('onPrimary'),
      primaryContainer: role('primaryContainer'),
      onPrimaryContainer: role('onPrimaryContainer'),
      primaryFixed: role('primaryFixed'),
      primaryFixedDim: role('primaryFixedDim'),
      onPrimaryFixed: role('onPrimaryFixed'),
      onPrimaryFixedVariant: role('onPrimaryFixedVariant'),
      secondary: role('secondary'),
      onSecondary: role('onSecondary'),
      secondaryContainer: role('secondaryContainer'),
      onSecondaryContainer: role('onSecondaryContainer'),
      secondaryFixed: role('secondaryFixed'),
      secondaryFixedDim: role('secondaryFixedDim'),
      onSecondaryFixed: role('onSecondaryFixed'),
      onSecondaryFixedVariant: role('onSecondaryFixedVariant'),
      tertiary: role('tertiary'),
      onTertiary: role('onTertiary'),
      tertiaryContainer: role('tertiaryContainer'),
      onTertiaryContainer: role('onTertiaryContainer'),
      tertiaryFixed: role('tertiaryFixed'),
      tertiaryFixedDim: role('tertiaryFixedDim'),
      onTertiaryFixed: role('onTertiaryFixed'),
      onTertiaryFixedVariant: role('onTertiaryFixedVariant'),
      error: role('error'),
      onError: role('onError'),
      errorContainer: role('errorContainer'),
      onErrorContainer: role('onErrorContainer'),
      surface: role('surface'),
      onSurface: role('onSurface'),
      surfaceDim: role('surfaceDim'),
      surfaceBright: role('surfaceBright'),
      surfaceContainerLowest: role('surfaceContainerLowest'),
      surfaceContainerLow: role('surfaceContainerLow'),
      surfaceContainer: role('surfaceContainer'),
      surfaceContainerHigh: role('surfaceContainerHigh'),
      surfaceContainerHighest: role('surfaceContainerHighest'),
      onSurfaceVariant: role('onSurfaceVariant'),
      outline: role('outline'),
      outlineVariant: role('outlineVariant'),
      shadow: role('shadow'),
      scrim: role('scrim'),
      inverseSurface: role('inverseSurface'),
      onInverseSurface: role('onInverseSurface'),
      inversePrimary: role('inversePrimary'),
      surfaceTint: role('surfaceTint'),
    );
  }
}
