import 'dart:typed_data';

import 'package:fixnum/fixnum.dart';
import 'package:server_box/src/proto/tombstone.pb.dart' as pb;

/// Reads the tombstone Android writes when a process dies of a native crash.
///
/// `ApplicationExitInfo.getTraceInputStream()` answers plain text for an ANR
/// and, from API 31, a `Tombstone` protocol buffer for `REASON_CRASH_NATIVE`.
/// Without this, such a report carries the word `crash_native` and nothing
/// else — which says a crash happened in native code and not where, and the
/// native code in this app is the Rust FFI, the Linux engine, proot and
/// sqlite.
///
/// The message is decoded by `lib/src/proto`, generated by `protoc` from
/// `third_party/proto/tombstone.proto` — AOSP's own schema, vendored — so
/// nothing here knows a field number and there is no wire format to get wrong.
/// See that directory's README for the regeneration command.
///
/// **In Dart rather than Kotlin**, which is the decision this file is really
/// making. Decoding on the platform side would mean `protobuf-javalite` and
/// the protobuf Gradle plugin in the module F-Droid rebuilds from source and
/// `androidReproducible` compares byte for byte — a dependency and a code
/// generator on the release path. It would also be reachable only from a
/// device that has already crashed, where a silent mistake costs the report it
/// was added to produce. Here the platform side hands over the bytes and this
/// is covered by `flutter test`.
abstract final class Tombstone {
  /// The crash, as the text a tombstone is usually read as.
  ///
  /// Null when the bytes carry nothing worth printing, and null on any failure
  /// to read them at all. The width of that catch is deliberate.
  ///
  /// `fromBuffer` documents `InvalidProtocolBufferException`, but a truncated
  /// record is as likely to run off the end of the byte list first and come
  /// out as a `RangeError` — which is an `Error`, so `on Exception` would not
  /// hold it. That is not hypothetical: it is what a prefix of a valid
  /// tombstone does, and a partial record is the ordinary case here, because
  /// these live in a global circular buffer another app's crash can evict half
  /// of.
  ///
  /// Where this runs is the other half of the argument. It is the launch after
  /// a crash, inside the code whose job is to report that crash: throwing
  /// would abandon the rest of `NativeExitReport.apply`, and the crash the
  /// user actually hit would go unreported because its *stack* could not be
  /// read. A report with no stack is what an evicted tombstone gives too, and
  /// it is still worth having.
  static String? decode(Uint8List bytes) {
    try {
      return _format(pb.Tombstone.fromBuffer(bytes));
    } catch (_) {
      return null;
    }
  }

  /// How many frames of the crashing thread are kept.
  ///
  /// A real backtrace is well inside this. The cap is what stops a runaway
  /// recursion — the one crash whose stack is unbounded — from being pasted
  /// into an issue in full.
  static const maxFrames = 64;

  static String? _format(pb.Tombstone t) {
    final lines = <String>[];

    // proto3 has no presence for scalars, so `hasX()` on a string or an int
    // answers "not the default" rather than "not written". The schema's own
    // note says to read the values rather than ask; `has` is used only for the
    // message fields, where it means what it says.
    if (t.hasSignalInfo()) lines.add(_signal(t.signalInfo));
    if (t.abortMessage.isNotEmpty) {
      lines.add("Abort message: '${t.abortMessage}'");
    }
    for (final cause in t.causes) {
      if (cause.humanReadable.isNotEmpty) lines.add('Cause: ${cause.humanReadable}');
    }

    final found = _crashingThread(t);
    if (found != null) {
      final (thread, isCrashing) = found;
      lines.add(
        [
          'pid: ${t.pid}',
          'tid: ${thread.id}',
          if (thread.name.isNotEmpty) 'name: ${thread.name}',
          if (!isCrashing) '(crashing thread ${t.tid} not in the record)',
        ].join(', '),
      );
      final frames = thread.currentBacktrace;
      var i = 0;
      for (final frame in frames.take(maxFrames)) {
        lines.add(_frame(frame, i++));
      }
      if (frames.length > maxFrames) {
        lines.add('    ... ${frames.length - maxFrames} more frames');
      }
    }

    // Nothing worth printing is not an empty report, it is no report — the
    // caller keeps the reason it already has rather than appending a blank
    // section to the log.
    return lines.isEmpty ? null : lines.join('\n');
  }

  /// The thread that died, and whether it is the one the record named.
  ///
  /// The crashing thread is named by `tid`. When its entry is missing — a
  /// partial record, or a tombstone written for a thread not in the map — any
  /// thread with a stack is better than no stack, and the header says which
  /// one was used so the reader is not left to assume.
  static (pb.Thread, bool)? _crashingThread(pb.Tombstone t) {
    final wanted = t.threads[t.tid];
    if (wanted != null) return (wanted, true);
    for (final thread in t.threads.values) {
      if (thread.currentBacktrace.isNotEmpty) return (thread, false);
    }
    return null;
  }

  /// The line a tombstone opens with, in the shape it is usually read in.
  ///
  /// `fault addr` is printed only when the record says there is one:
  /// `has_fault_address` is false for a SIGABRT, where the zero in
  /// `fault_address` would otherwise read as a null dereference. That field is
  /// an explicit bool in the schema for exactly this reason, and is the one
  /// place where asking rather than reading is right.
  static String _signal(pb.Signal s) {
    final buf = StringBuffer('signal ${s.number}');
    if (s.name.isNotEmpty) buf.write(' (${s.name})');
    buf.write(', code ${s.code}');
    if (s.codeName.isNotEmpty) buf.write(' (${s.codeName})');
    // `faultAddress_9` is the generator's doing, not a typo: the schema has
    // both `has_fault_address` and `fault_address`, and the first one's getter
    // takes the name the second one's presence method would have had, so the
    // second is suffixed with its field number. Renaming it means editing
    // generated code, which the next regeneration would undo.
    if (s.hasFaultAddress) {
      buf.write(', fault addr 0x${_hex64(s.faultAddress_9)}');
    }
    return buf.toString();
  }

  /// One frame, in the layout `debuggerd` prints.
  ///
  /// `rel_pc` rather than `pc`: the offset within the mapped file is what a
  /// symbol resolves against, while the runtime address means nothing without
  /// the mapping it fell in.
  ///
  /// The build id is kept because it is what pairs a frame with the symbols
  /// archived by CI: the same library built twice has the same path and a
  /// different id, and resolving against the wrong one gives names that are
  /// wrong rather than missing.
  static String _frame(pb.BacktraceFrame f, int index) {
    final buf = StringBuffer('    #${index.toString().padLeft(2, '0')} ');
    buf.write('pc ${_hex64(f.relPc)}  ');
    buf.write(f.fileName.isNotEmpty ? f.fileName : '<anonymous>');
    if (f.functionName.isNotEmpty) {
      buf.write(' (${f.functionName}');
      if (f.functionOffset != Int64.ZERO) buf.write('+${f.functionOffset}');
      buf.write(')');
    }
    if (f.buildId.isNotEmpty) buf.write(' (BuildId: ${f.buildId})');
    return buf.toString();
  }

  /// Sixteen hex digits, unsigned.
  ///
  /// The schema's addresses are `uint64` and arrive as a signed [Int64], so an
  /// address at or above 2^63 is negative and `toRadixString` would write it
  /// with a leading minus.
  static String _hex64(Int64 value) =>
      value.toRadixStringUnsigned(16).padLeft(16, '0');
}
