// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:server_box/src/rust/api/bmc.dart';
import 'package:server_box/src/rust/api/create.dart';
import 'package:server_box/src/rust/api/desktop.dart';
import 'package:server_box/src/rust/api/file.dart';
import 'package:server_box/src/rust/api/hardware.dart';
import 'package:server_box/src/rust/api/parser.dart';
import 'package:server_box/src/rust/api/pve.dart';
import 'package:server_box/src/rust/api/remote_desktop.dart';
import 'package:server_box/src/rust/api/resource.dart';
import 'package:server_box/src/rust/api/script.dart';
import 'package:server_box/src/rust/api/snippet.dart';
import 'package:server_box/src/rust/api/ssh_asym.dart';
import 'package:server_box/src/rust/api/ssh_crypto.dart';
import 'package:server_box/src/rust/api/users.dart';
import 'package:server_box/src/rust/api/virt.dart';
import 'package:server_box/src/rust/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BmcClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClientPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LibvirtRatesPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRatesPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PowerWatchPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatchPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PveSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSessionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RemoteDesktopSessionHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SshBlockCipherPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipherPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SshMacPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMacPtr;

  @protected
  BmcClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    dynamic raw,
  );

  @protected
  LibvirtRates
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    dynamic raw,
  );

  @protected
  PowerWatch
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    dynamic raw,
  );

  @protected
  PveSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    dynamic raw,
  );

  @protected
  RemoteDesktopSessionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    dynamic raw,
  );

  @protected
  SshBlockCipher
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    dynamic raw,
  );

  @protected
  SshMac
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    dynamic raw,
  );

  @protected
  LibvirtRates
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    dynamic raw,
  );

  @protected
  PowerWatch
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    dynamic raw,
  );

  @protected
  SshBlockCipher
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    dynamic raw,
  );

  @protected
  BmcClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    dynamic raw,
  );

  @protected
  PveSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    dynamic raw,
  );

  @protected
  RemoteDesktopSessionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    dynamic raw,
  );

  @protected
  SshBlockCipher
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    dynamic raw,
  );

  @protected
  SshMac
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  BmcClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    dynamic raw,
  );

  @protected
  LibvirtRates
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    dynamic raw,
  );

  @protected
  PowerWatch
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    dynamic raw,
  );

  @protected
  PveSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    dynamic raw,
  );

  @protected
  RemoteDesktopSessionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    dynamic raw,
  );

  @protected
  SshBlockCipher
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    dynamic raw,
  );

  @protected
  SshMac
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BmcError dco_decode_bmc_error(dynamic raw);

  @protected
  BmcOutcome dco_decode_bmc_outcome(dynamic raw);

  @protected
  BmcReading dco_decode_bmc_reading(dynamic raw);

  @protected
  BmcSensors dco_decode_bmc_sensors(dynamic raw);

  @protected
  BmcSnapshot dco_decode_bmc_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CertInfo dco_decode_box_autoadd_cert_info(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  LibvirtPoolRef dco_decode_box_autoadd_libvirt_pool_ref(dynamic raw);

  @protected
  PveGuestRef dco_decode_box_autoadd_pve_guest_ref(dynamic raw);

  @protected
  PveLogin dco_decode_box_autoadd_pve_login(dynamic raw);

  @protected
  PveTiming dco_decode_box_autoadd_pve_timing(dynamic raw);

  @protected
  RdpSessionParams dco_decode_box_autoadd_rdp_session_params(dynamic raw);

  @protected
  RedfishChassis dco_decode_box_autoadd_redfish_chassis(dynamic raw);

  @protected
  RedfishSystem dco_decode_box_autoadd_redfish_system(dynamic raw);

  @protected
  RedfishTopology dco_decode_box_autoadd_redfish_topology(dynamic raw);

  @protected
  RemoteDesktopEvent dco_decode_box_autoadd_remote_desktop_event(dynamic raw);

  @protected
  ResetRequest dco_decode_box_autoadd_reset_request(dynamic raw);

  @protected
  SnapshotNameIssue dco_decode_box_autoadd_snapshot_name_issue(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VncSessionParams dco_decode_box_autoadd_vnc_session_params(dynamic raw);

  @protected
  CertInfo dco_decode_box_cert_info(dynamic raw);

  @protected
  CertInfo dco_decode_cert_info(dynamic raw);

  @protected
  CommandSpec dco_decode_command_spec(dynamic raw);

  @protected
  CustomCmd dco_decode_custom_cmd(dynamic raw);

  @protected
  EcdsaSignature dco_decode_ecdsa_signature(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibvirtPoolRef dco_decode_libvirt_pool_ref(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BmcReading> dco_decode_list_bmc_reading(dynamic raw);

  @protected
  List<CommandSpec> dco_decode_list_command_spec(dynamic raw);

  @protected
  List<CustomCmd> dco_decode_list_custom_cmd(dynamic raw);

  @protected
  List<LibvirtPoolRef> dco_decode_list_libvirt_pool_ref(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PveHeader> dco_decode_list_pve_header(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<ScriptSegment> dco_decode_list_script_segment(dynamic raw);

  @protected
  List<VirtActionKind> dco_decode_list_virt_action_kind(dynamic raw);

  @protected
  List<VirtOverlay> dco_decode_list_virt_overlay(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CertInfo? dco_decode_opt_box_autoadd_cert_info(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  RedfishChassis? dco_decode_opt_box_autoadd_redfish_chassis(dynamic raw);

  @protected
  RedfishSystem? dco_decode_opt_box_autoadd_redfish_system(dynamic raw);

  @protected
  RedfishTopology? dco_decode_opt_box_autoadd_redfish_topology(dynamic raw);

  @protected
  RemoteDesktopEvent? dco_decode_opt_box_autoadd_remote_desktop_event(
    dynamic raw,
  );

  @protected
  ResetRequest? dco_decode_opt_box_autoadd_reset_request(dynamic raw);

  @protected
  SnapshotNameIssue? dco_decode_opt_box_autoadd_snapshot_name_issue(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  CertInfo? dco_decode_opt_box_cert_info(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<CustomCmd>? dco_decode_opt_list_custom_cmd(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<VirtActionKind>? dco_decode_opt_list_virt_action_kind(dynamic raw);

  @protected
  PowerIntent dco_decode_power_intent(dynamic raw);

  @protected
  PowerState dco_decode_power_state(dynamic raw);

  @protected
  PveConsoleKind dco_decode_pve_console_kind(dynamic raw);

  @protected
  PveConsoleTicket dco_decode_pve_console_ticket(dynamic raw);

  @protected
  PveError dco_decode_pve_error(dynamic raw);

  @protected
  PveGuestRef dco_decode_pve_guest_ref(dynamic raw);

  @protected
  PveHeader dco_decode_pve_header(dynamic raw);

  @protected
  PveHistoryWindow dco_decode_pve_history_window(dynamic raw);

  @protected
  PveLogin dco_decode_pve_login(dynamic raw);

  @protected
  PveMethod dco_decode_pve_method(dynamic raw);

  @protected
  PveRawResponse dco_decode_pve_raw_response(dynamic raw);

  @protected
  PveTiming dco_decode_pve_timing(dynamic raw);

  @protected
  RdpSessionParams dco_decode_rdp_session_params(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RedfishChassis dco_decode_redfish_chassis(dynamic raw);

  @protected
  RedfishFailure dco_decode_redfish_failure(dynamic raw);

  @protected
  RedfishRoot dco_decode_redfish_root(dynamic raw);

  @protected
  RedfishSystem dco_decode_redfish_system(dynamic raw);

  @protected
  RedfishTopology dco_decode_redfish_topology(dynamic raw);

  @protected
  RemoteDesktopConnectionState dco_decode_remote_desktop_connection_state(
    dynamic raw,
  );

  @protected
  RemoteDesktopEndReason dco_decode_remote_desktop_end_reason(dynamic raw);

  @protected
  RemoteDesktopEvent dco_decode_remote_desktop_event(dynamic raw);

  @protected
  ResetRequest dco_decode_reset_request(dynamic raw);

  @protected
  ScriptSegment dco_decode_script_segment(dynamic raw);

  @protected
  ShellFuncKind dco_decode_shell_func_kind(dynamic raw);

  @protected
  SnapshotMemoryKind dco_decode_snapshot_memory_kind(dynamic raw);

  @protected
  SnapshotNameIssue dco_decode_snapshot_name_issue(dynamic raw);

  @protected
  SnippetFfiError dco_decode_snippet_ffi_error(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserFfiError dco_decode_user_ffi_error(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VirtActionKind dco_decode_virt_action_kind(dynamic raw);

  @protected
  VirtDeletePlan dco_decode_virt_delete_plan(dynamic raw);

  @protected
  VirtErrorKind dco_decode_virt_error_kind(dynamic raw);

  @protected
  VirtFailure dco_decode_virt_failure(dynamic raw);

  @protected
  VirtFfiError dco_decode_virt_ffi_error(dynamic raw);

  @protected
  VirtOverlay dco_decode_virt_overlay(dynamic raw);

  @protected
  VirtResourceScript dco_decode_virt_resource_script(dynamic raw);

  @protected
  VirtUploadEntryKind dco_decode_virt_upload_entry_kind(dynamic raw);

  @protected
  VncSessionParams dco_decode_vnc_session_params(dynamic raw);

  @protected
  X25519KeyPair dco_decode_x_25519_key_pair(dynamic raw);

  @protected
  BmcClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    SseDeserializer deserializer,
  );

  @protected
  LibvirtRates
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    SseDeserializer deserializer,
  );

  @protected
  PowerWatch
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    SseDeserializer deserializer,
  );

  @protected
  PveSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopSessionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  SshBlockCipher
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SseDeserializer deserializer,
  );

  @protected
  SshMac
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SseDeserializer deserializer,
  );

  @protected
  LibvirtRates
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    SseDeserializer deserializer,
  );

  @protected
  PowerWatch
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    SseDeserializer deserializer,
  );

  @protected
  SshBlockCipher
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SseDeserializer deserializer,
  );

  @protected
  BmcClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    SseDeserializer deserializer,
  );

  @protected
  PveSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopSessionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  SshBlockCipher
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SseDeserializer deserializer,
  );

  @protected
  SshMac
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  BmcClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    SseDeserializer deserializer,
  );

  @protected
  LibvirtRates
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    SseDeserializer deserializer,
  );

  @protected
  PowerWatch
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    SseDeserializer deserializer,
  );

  @protected
  PveSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopSessionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    SseDeserializer deserializer,
  );

  @protected
  SshBlockCipher
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SseDeserializer deserializer,
  );

  @protected
  SshMac
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BmcError sse_decode_bmc_error(SseDeserializer deserializer);

  @protected
  BmcOutcome sse_decode_bmc_outcome(SseDeserializer deserializer);

  @protected
  BmcReading sse_decode_bmc_reading(SseDeserializer deserializer);

  @protected
  BmcSensors sse_decode_bmc_sensors(SseDeserializer deserializer);

  @protected
  BmcSnapshot sse_decode_bmc_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CertInfo sse_decode_box_autoadd_cert_info(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  LibvirtPoolRef sse_decode_box_autoadd_libvirt_pool_ref(
    SseDeserializer deserializer,
  );

  @protected
  PveGuestRef sse_decode_box_autoadd_pve_guest_ref(
    SseDeserializer deserializer,
  );

  @protected
  PveLogin sse_decode_box_autoadd_pve_login(SseDeserializer deserializer);

  @protected
  PveTiming sse_decode_box_autoadd_pve_timing(SseDeserializer deserializer);

  @protected
  RdpSessionParams sse_decode_box_autoadd_rdp_session_params(
    SseDeserializer deserializer,
  );

  @protected
  RedfishChassis sse_decode_box_autoadd_redfish_chassis(
    SseDeserializer deserializer,
  );

  @protected
  RedfishSystem sse_decode_box_autoadd_redfish_system(
    SseDeserializer deserializer,
  );

  @protected
  RedfishTopology sse_decode_box_autoadd_redfish_topology(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopEvent sse_decode_box_autoadd_remote_desktop_event(
    SseDeserializer deserializer,
  );

  @protected
  ResetRequest sse_decode_box_autoadd_reset_request(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotNameIssue sse_decode_box_autoadd_snapshot_name_issue(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VncSessionParams sse_decode_box_autoadd_vnc_session_params(
    SseDeserializer deserializer,
  );

  @protected
  CertInfo sse_decode_box_cert_info(SseDeserializer deserializer);

  @protected
  CertInfo sse_decode_cert_info(SseDeserializer deserializer);

  @protected
  CommandSpec sse_decode_command_spec(SseDeserializer deserializer);

  @protected
  CustomCmd sse_decode_custom_cmd(SseDeserializer deserializer);

  @protected
  EcdsaSignature sse_decode_ecdsa_signature(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibvirtPoolRef sse_decode_libvirt_pool_ref(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BmcReading> sse_decode_list_bmc_reading(SseDeserializer deserializer);

  @protected
  List<CommandSpec> sse_decode_list_command_spec(SseDeserializer deserializer);

  @protected
  List<CustomCmd> sse_decode_list_custom_cmd(SseDeserializer deserializer);

  @protected
  List<LibvirtPoolRef> sse_decode_list_libvirt_pool_ref(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PveHeader> sse_decode_list_pve_header(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<ScriptSegment> sse_decode_list_script_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<VirtActionKind> sse_decode_list_virt_action_kind(
    SseDeserializer deserializer,
  );

  @protected
  List<VirtOverlay> sse_decode_list_virt_overlay(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CertInfo? sse_decode_opt_box_autoadd_cert_info(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  RedfishChassis? sse_decode_opt_box_autoadd_redfish_chassis(
    SseDeserializer deserializer,
  );

  @protected
  RedfishSystem? sse_decode_opt_box_autoadd_redfish_system(
    SseDeserializer deserializer,
  );

  @protected
  RedfishTopology? sse_decode_opt_box_autoadd_redfish_topology(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopEvent? sse_decode_opt_box_autoadd_remote_desktop_event(
    SseDeserializer deserializer,
  );

  @protected
  ResetRequest? sse_decode_opt_box_autoadd_reset_request(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotNameIssue? sse_decode_opt_box_autoadd_snapshot_name_issue(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CertInfo? sse_decode_opt_box_cert_info(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<CustomCmd>? sse_decode_opt_list_custom_cmd(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<VirtActionKind>? sse_decode_opt_list_virt_action_kind(
    SseDeserializer deserializer,
  );

  @protected
  PowerIntent sse_decode_power_intent(SseDeserializer deserializer);

  @protected
  PowerState sse_decode_power_state(SseDeserializer deserializer);

  @protected
  PveConsoleKind sse_decode_pve_console_kind(SseDeserializer deserializer);

  @protected
  PveConsoleTicket sse_decode_pve_console_ticket(SseDeserializer deserializer);

  @protected
  PveError sse_decode_pve_error(SseDeserializer deserializer);

  @protected
  PveGuestRef sse_decode_pve_guest_ref(SseDeserializer deserializer);

  @protected
  PveHeader sse_decode_pve_header(SseDeserializer deserializer);

  @protected
  PveHistoryWindow sse_decode_pve_history_window(SseDeserializer deserializer);

  @protected
  PveLogin sse_decode_pve_login(SseDeserializer deserializer);

  @protected
  PveMethod sse_decode_pve_method(SseDeserializer deserializer);

  @protected
  PveRawResponse sse_decode_pve_raw_response(SseDeserializer deserializer);

  @protected
  PveTiming sse_decode_pve_timing(SseDeserializer deserializer);

  @protected
  RdpSessionParams sse_decode_rdp_session_params(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RedfishChassis sse_decode_redfish_chassis(SseDeserializer deserializer);

  @protected
  RedfishFailure sse_decode_redfish_failure(SseDeserializer deserializer);

  @protected
  RedfishRoot sse_decode_redfish_root(SseDeserializer deserializer);

  @protected
  RedfishSystem sse_decode_redfish_system(SseDeserializer deserializer);

  @protected
  RedfishTopology sse_decode_redfish_topology(SseDeserializer deserializer);

  @protected
  RemoteDesktopConnectionState sse_decode_remote_desktop_connection_state(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopEndReason sse_decode_remote_desktop_end_reason(
    SseDeserializer deserializer,
  );

  @protected
  RemoteDesktopEvent sse_decode_remote_desktop_event(
    SseDeserializer deserializer,
  );

  @protected
  ResetRequest sse_decode_reset_request(SseDeserializer deserializer);

  @protected
  ScriptSegment sse_decode_script_segment(SseDeserializer deserializer);

  @protected
  ShellFuncKind sse_decode_shell_func_kind(SseDeserializer deserializer);

  @protected
  SnapshotMemoryKind sse_decode_snapshot_memory_kind(
    SseDeserializer deserializer,
  );

  @protected
  SnapshotNameIssue sse_decode_snapshot_name_issue(
    SseDeserializer deserializer,
  );

  @protected
  SnippetFfiError sse_decode_snippet_ffi_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserFfiError sse_decode_user_ffi_error(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VirtActionKind sse_decode_virt_action_kind(SseDeserializer deserializer);

  @protected
  VirtDeletePlan sse_decode_virt_delete_plan(SseDeserializer deserializer);

  @protected
  VirtErrorKind sse_decode_virt_error_kind(SseDeserializer deserializer);

  @protected
  VirtFailure sse_decode_virt_failure(SseDeserializer deserializer);

  @protected
  VirtFfiError sse_decode_virt_ffi_error(SseDeserializer deserializer);

  @protected
  VirtOverlay sse_decode_virt_overlay(SseDeserializer deserializer);

  @protected
  VirtResourceScript sse_decode_virt_resource_script(
    SseDeserializer deserializer,
  );

  @protected
  VirtUploadEntryKind sse_decode_virt_upload_entry_kind(
    SseDeserializer deserializer,
  );

  @protected
  VncSessionParams sse_decode_vnc_session_params(SseDeserializer deserializer);

  @protected
  X25519KeyPair sse_decode_x_25519_key_pair(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    BmcClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    LibvirtRates self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    PowerWatch self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    PveSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    RemoteDesktopSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SshBlockCipher self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SshMac self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    LibvirtRates self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    PowerWatch self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SshBlockCipher self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    BmcClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    PveSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    RemoteDesktopSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SshBlockCipher self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SshMac self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    BmcClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    LibvirtRates self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    PowerWatch self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    PveSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    RemoteDesktopSessionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    SshBlockCipher self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    SshMac self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bmc_error(BmcError self, SseSerializer serializer);

  @protected
  void sse_encode_bmc_outcome(BmcOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_bmc_reading(BmcReading self, SseSerializer serializer);

  @protected
  void sse_encode_bmc_sensors(BmcSensors self, SseSerializer serializer);

  @protected
  void sse_encode_bmc_snapshot(BmcSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cert_info(
    CertInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_libvirt_pool_ref(
    LibvirtPoolRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pve_guest_ref(
    PveGuestRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pve_login(
    PveLogin self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pve_timing(
    PveTiming self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rdp_session_params(
    RdpSessionParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_redfish_chassis(
    RedfishChassis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_redfish_system(
    RedfishSystem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_redfish_topology(
    RedfishTopology self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_desktop_event(
    RemoteDesktopEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reset_request(
    ResetRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_snapshot_name_issue(
    SnapshotNameIssue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vnc_session_params(
    VncSessionParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_cert_info(CertInfo self, SseSerializer serializer);

  @protected
  void sse_encode_cert_info(CertInfo self, SseSerializer serializer);

  @protected
  void sse_encode_command_spec(CommandSpec self, SseSerializer serializer);

  @protected
  void sse_encode_custom_cmd(CustomCmd self, SseSerializer serializer);

  @protected
  void sse_encode_ecdsa_signature(
    EcdsaSignature self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_libvirt_pool_ref(
    LibvirtPoolRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bmc_reading(
    List<BmcReading> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_command_spec(
    List<CommandSpec> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_cmd(
    List<CustomCmd> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_libvirt_pool_ref(
    List<LibvirtPoolRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pve_header(
    List<PveHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_script_segment(
    List<ScriptSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_virt_action_kind(
    List<VirtActionKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_virt_overlay(
    List<VirtOverlay> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cert_info(
    CertInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_redfish_chassis(
    RedfishChassis? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_redfish_system(
    RedfishSystem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_redfish_topology(
    RedfishTopology? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_desktop_event(
    RemoteDesktopEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reset_request(
    ResetRequest? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_snapshot_name_issue(
    SnapshotNameIssue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_cert_info(CertInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_custom_cmd(
    List<CustomCmd>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_virt_action_kind(
    List<VirtActionKind>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_power_intent(PowerIntent self, SseSerializer serializer);

  @protected
  void sse_encode_power_state(PowerState self, SseSerializer serializer);

  @protected
  void sse_encode_pve_console_kind(
    PveConsoleKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pve_console_ticket(
    PveConsoleTicket self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pve_error(PveError self, SseSerializer serializer);

  @protected
  void sse_encode_pve_guest_ref(PveGuestRef self, SseSerializer serializer);

  @protected
  void sse_encode_pve_header(PveHeader self, SseSerializer serializer);

  @protected
  void sse_encode_pve_history_window(
    PveHistoryWindow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pve_login(PveLogin self, SseSerializer serializer);

  @protected
  void sse_encode_pve_method(PveMethod self, SseSerializer serializer);

  @protected
  void sse_encode_pve_raw_response(
    PveRawResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pve_timing(PveTiming self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_session_params(
    RdpSessionParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_redfish_chassis(
    RedfishChassis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_redfish_failure(
    RedfishFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_redfish_root(RedfishRoot self, SseSerializer serializer);

  @protected
  void sse_encode_redfish_system(RedfishSystem self, SseSerializer serializer);

  @protected
  void sse_encode_redfish_topology(
    RedfishTopology self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_desktop_connection_state(
    RemoteDesktopConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_desktop_end_reason(
    RemoteDesktopEndReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_desktop_event(
    RemoteDesktopEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reset_request(ResetRequest self, SseSerializer serializer);

  @protected
  void sse_encode_script_segment(ScriptSegment self, SseSerializer serializer);

  @protected
  void sse_encode_shell_func_kind(ShellFuncKind self, SseSerializer serializer);

  @protected
  void sse_encode_snapshot_memory_kind(
    SnapshotMemoryKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_snapshot_name_issue(
    SnapshotNameIssue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_snippet_ffi_error(
    SnippetFfiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_ffi_error(UserFfiError self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_virt_action_kind(
    VirtActionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_virt_delete_plan(
    VirtDeletePlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_virt_error_kind(VirtErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_virt_failure(VirtFailure self, SseSerializer serializer);

  @protected
  void sse_encode_virt_ffi_error(VirtFfiError self, SseSerializer serializer);

  @protected
  void sse_encode_virt_overlay(VirtOverlay self, SseSerializer serializer);

  @protected
  void sse_encode_virt_resource_script(
    VirtResourceScript self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_virt_upload_entry_kind(
    VirtUploadEntryKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vnc_session_params(
    VncSessionParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_x_25519_key_pair(
    X25519KeyPair self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBmcClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRatesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRatesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRatesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRates =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLibvirtRatesPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatchPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatchPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatchPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatch =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPowerWatchPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPveSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRemoteDesktopSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipherPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipherPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipher =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshBlockCipherPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMacPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMacPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMacPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_server_box_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMac =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshMacPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
