/// The lollipopkit Design System for the desk: tokens and `lk-*` styles in
/// `lk.css`, these components on top. Apps build their UI from these (see
/// `desk/CLAUDE.md`); glyph names are Material Symbols Rounded.

export { default as Icon } from './Icon.svelte'
export { default as Button } from './Button.svelte'
export { default as IconButton } from './IconButton.svelte'
export { default as Badge, type BadgeTone } from './Badge.svelte'
export { default as Input } from './Input.svelte'
export { default as Textarea } from './Textarea.svelte'
export { default as Select } from './Select.svelte'
export { default as Checkbox } from './Checkbox.svelte'
export { default as Radio } from './Radio.svelte'
export { default as Switch } from './Switch.svelte'
export { default as Slider } from './Slider.svelte'
export { default as Spinner } from './Spinner.svelte'
export { default as SegmentedControl } from './SegmentedControl.svelte'
export { default as Card } from './Card.svelte'
export { default as Tooltip } from './Tooltip.svelte'
export { default as Dialog } from './Dialog.svelte'
export { default as Notification } from './Notification.svelte'
export { default as Menu, type MenuEntry } from './Menu.svelte'
export { default as AppIcon, type IconTone } from './AppIcon.svelte'
export { default as WindowControls } from './WindowControls.svelte'
export { default as SidebarSection } from './SidebarSection.svelte'
export { default as SidebarItem } from './SidebarItem.svelte'
export { default as ControlTile } from './ControlTile.svelte'
export { default as Group } from './Group.svelte' // SettingsGroup
export { default as Row } from './Row.svelte' // SettingsRow
export { default as DataTable, type Column, type TableSort } from './DataTable.svelte'
export { default as StatTile } from './StatTile.svelte'
export { default as LegendChip } from './LegendChip.svelte'
export { default as SearchField } from './SearchField.svelte'
export { default as ToolbarGroup, type ToolbarItem } from './ToolbarGroup.svelte'
export { default as StatusBar } from './StatusBar.svelte'
export { default as NotificationCenter, type CenterNotice } from './NotificationCenter.svelte'
export { default as TitleTabs, type TitleTab } from './TitleTabs.svelte'
export { default as Indicator } from './Indicator.svelte'
export { viewEnter, viewIn } from './motion'
