import 'package:toolbox/data/model/cpu_2_status.dart';
import 'package:toolbox/data/model/disk_info.dart';
import 'package:toolbox/data/model/tcp_status.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ServerStatus {
/*
{
  "cpuPercent": 0,
  "memList": [
    1
  ],
  "sysVer": "",
  "uptime": "",
  "disk": [
    {
      "mountPath": "",
      "mountLocation": "",
      "usedPercent": 0,
      "used": "",
      "size": "",
      "avail": ""
    }
  ]
} 
*/

  Cpu2Status? cpu2Status;
  List<int?>? memList;
  String? sysVer;
  String? uptime;
  List<DiskInfo?>? disk;
  TcpStatus? tcp;

  ServerStatus(
      {this.cpu2Status,
      this.memList,
      this.sysVer,
      this.uptime,
      this.disk,
      this.tcp});
}
