import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ServerPrivateInfo {
/*
{
  "ip": "",
  "port": 1,
  "user": "",
  "authorization": ""
} 
*/

  late String name;
  late String ip;
  late int port;
  late String user;
  late String pwd;
  String? pubKeyId;

  ServerPrivateInfo(
      {required this.name,
      required this.ip,
      required this.port,
      required this.user,
      required this.pwd,
      this.pubKeyId});
  ServerPrivateInfo.fromJson(Map<String, dynamic> json) {
    name = json["name"].toString();
    ip = json["ip"].toString();
    port = json["port"].toInt();
    user = json["user"].toString();
    pwd = json["authorization"].toString();
    pubKeyId = json["pubKeyId"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["name"] = name;
    data["ip"] = ip;
    data["port"] = port;
    data["user"] = user;
    data["authorization"] = pwd;
    data["pubKeyId"] = pubKeyId;
    return data;
  }
}

List<ServerPrivateInfo> getServerInfoList(dynamic data) {
  List<ServerPrivateInfo> ss = [];
  if (data is String) {
    data = json.decode(data);
  }
  for (var t in data) {
    ss.add(ServerPrivateInfo.fromJson(t));
  }

  return ss;
}
