/// Pure utility for building tmux commands.
///
/// Extracted from TmuxSession for testability without flutter dependencies.
abstract final class TmuxCommandBuilder {
  /// Escape a shell argument for use in tmux commands.
  static String escapeArg(String arg) {
    return "'${arg.replaceAll("'", "'\\''")}'";
  }

  static String tmuxPrefix({String tmuxBin = 'tmux'}) {
    return escapeArg(tmuxBin);
  }

  /// Build the prefix for a tmux client attached to ServerBox's terminal.
  ///
  /// `-CC` is the tmux control-mode protocol. ServerBox decodes it and renders
  /// the active pane itself, rather than showing tmux's terminal UI.
  static String _tmuxClientPrefix({String tmuxBin = 'tmux'}) {
    return '${tmuxPrefix(tmuxBin: tmuxBin)} -u -CC';
  }

  /// Build the prefix for one-shot tmux discovery commands.
  ///
  /// `-u` is not only about the pane's Unicode rendering. Without it, tmux in
  /// a non-UTF-8 locale can replace tab separators in formatted output with
  /// `_`, which breaks the app's discovery parser. The attached client already
  /// uses the same flag.
  static String _tmuxDiscoveryPrefix({String tmuxBin = 'tmux'}) {
    return '${tmuxPrefix(tmuxBin: tmuxBin)} -u';
  }

  /// Build the attach command for an existing session target.
  ///
  /// Prefer a stable `$id` target. A name is accepted for legacy restore state,
  /// but `:` in a name would otherwise be parsed as a session/window divider.
  static String attachSession(String sessionTarget, {String tmuxBin = 'tmux'}) {
    return '${_tmuxClientPrefix(tmuxBin: tmuxBin)} attach-session -t ${escapeArg(sessionTarget)}';
  }

  /// Build the attach command targeting a specific window.
  static String attachSessionWindow(
    String sessionTarget,
    int windowIndex, {
    String tmuxBin = 'tmux',
  }) {
    return '${_tmuxClientPrefix(tmuxBin: tmuxBin)} attach-session -t ${escapeArg('$sessionTarget:$windowIndex')}';
  }

  /// Build the new-session -A command (attach or create).
  static String newSessionOrAttach(
    String sessionName, {
    String tmuxBin = 'tmux',
  }) {
    return '${_tmuxClientPrefix(tmuxBin: tmuxBin)} new-session -A -s ${escapeArg(sessionName)}';
  }

  static const _shellTab = "\$(printf '\\t')";

  /// Build the list-sessions command with a stable, escaped format.
  ///
  /// The separator is generated by the remote shell with POSIX `printf`
  /// command substitution, not by a raw tab in the command text. That keeps
  /// the format portable across `sh`, `bash`, `zsh`, and `dash` while tmux
  /// still receives real tab separators in its argument.
  static String listSessionsCmd({String tmuxBin = 'tmux'}) =>
      '${_tmuxDiscoveryPrefix(tmuxBin: tmuxBin)} list-sessions -F '
      '"#{session_id}$_shellTab#{q:session_name}$_shellTab'
      '#{session_windows}$_shellTab#{session_attached}$_shellTab'
      '#{session_created_string}$_shellTab'
      '#{session_last_attached_string}$_shellTab'
      '#{session_activity_string}"';

  /// Build the list-windows command for a session.
  ///
  /// Discovery uses this only to validate a restored window before attach.
  /// Once the foreground client is attached, `TmuxControlClient` owns window
  /// and pane state over control mode.
  static String listWindows(String sessionTarget, {String tmuxBin = 'tmux'}) =>
      '${_tmuxDiscoveryPrefix(tmuxBin: tmuxBin)} list-windows -t ${escapeArg(sessionTarget)} -F '
      '"#{window_index}|#{window_name}|#{window_active}|#{window_panes}|#{window_activity_string}"';

  /// Locates tmux, including installations added to `PATH` by `.bashrc`.
  ///
  /// The direct probes remain as fallbacks when an interactive Bash shell is
  /// unavailable.
  static String get findTmux =>
      "bash -i -c 'command -v tmux' 2>/dev/null || "
      'command -v tmux 2>/dev/null || which tmux 2>/dev/null';
}
