// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/api/bmc.dart';
import 'package:server_box/src/rust/api/pve.dart';
import 'package:server_box/src/rust/frb_generated.dart';

/// Why `schedule` cannot be a backup job's, as an `Issue`'s name
/// (`schedule_invalid`); None when it has the shape of one PVE takes.
String? virtScheduleIssue({required String schedule}) =>
    RustLib.instance.api.crateApiBackupVirtScheduleIssue(schedule: schedule);

/// Whether `job_json` (a `BackupJob`) takes `vmid` and no other guest: the
/// guest's own plan.
bool virtBackupJobTakesOnly({required String jobJson, int? vmid}) => RustLib
    .instance
    .api
    .crateApiBackupVirtBackupJobTakesOnly(jobJson: jobJson, vmid: vmid);
