// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `document`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// POSIX `sh`, for `ServerExec.run(script, entry: 'sh')`.
String cronListScript() => RustLib.instance.api.crateApiCronCronListScript();

/// Takes the document on stdin. A single command: no entry.
String cronSaveCommand() => RustLib.instance.api.crateApiCronCronSaveCommand();

/// What [`cron_list_script`] produced. `succeeded` is the app's own verdict on
/// the run, which also knows about a broken stream.
CronListing cronReadListing({
  required String stdout,
  required String stderr,
  int? exitCode,
  required bool succeeded,
}) => RustLib.instance.api.crateApiCronCronReadListing(
  stdout: stdout,
  stderr: stderr,
  exitCode: exitCode,
  succeeded: succeeded,
);

/// Whether [`cron_save_command`] took the document.
void cronCheckSave({
  required String stdout,
  required String stderr,
  int? exitCode,
  required bool succeeded,
}) => RustLib.instance.api.crateApiCronCronCheckSave(
  stdout: stdout,
  stderr: stderr,
  exitCode: exitCode,
  succeeded: succeeded,
);

/// Replaces the job at `line_index` in `lines`, or appends one when it is
/// `None`.
CronDocumentData cronUpsert({
  required List<String> lines,
  int? lineIndex,
  required String schedule,
  required String command,
  required bool enabled,
}) => RustLib.instance.api.crateApiCronCronUpsert(
  lines: lines,
  lineIndex: lineIndex,
  schedule: schedule,
  command: command,
  enabled: enabled,
);

CronDocumentData cronRemove({
  required List<String> lines,
  required int lineIndex,
}) => RustLib.instance.api.crateApiCronCronRemove(
  lines: lines,
  lineIndex: lineIndex,
);

CronDocumentData cronSetEnabled({
  required List<String> lines,
  required int lineIndex,
  required bool enabled,
}) => RustLib.instance.api.crateApiCronCronSetEnabled(
  lines: lines,
  lineIndex: lineIndex,
  enabled: enabled,
);

/// What is wrong with the line these would make, as a
/// [`CronEditError::code`], or `None`.
String? cronValidate({required String schedule, required String command}) =>
    RustLib.instance.api.crateApiCronCronValidate(
      schedule: schedule,
      command: command,
    );

/// `None` for an expression this does not read; the app shows it as written.
CronScheduleFields? cronScheduleParse({required String expression}) =>
    RustLib.instance.api.crateApiCronCronScheduleParse(expression: expression);

/// The next minute `expression` runs, strictly after `from`; both on the
/// server's wall clock. `None` when it has none or is not read.
CronWall? cronNextRun({required String expression, required CronWall from}) =>
    RustLib.instance.api.crateApiCronCronNextRun(
      expression: expression,
      from: from,
    );

/// A crontab: every line, the jobs read out of them, the lines that are not
/// jobs (shown so a crontab another tool manages does not look like it lost
/// them), and the text that writes it back.
class CronDocumentData {
  final List<String> lines;
  final List<CronJobLine> jobs;
  final List<String> preserved;
  final String text;

  const CronDocumentData({
    required this.lines,
    required this.jobs,
    required this.preserved,
    required this.text,
  });

  @override
  int get hashCode =>
      lines.hashCode ^ jobs.hashCode ^ preserved.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronDocumentData &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          jobs == other.jobs &&
          preserved == other.preserved &&
          text == other.text;
}

/// An edit refused. `code` is `sbm_parser::cron::CronValidation`'s
/// (`scheduleEmpty`, `commandEmpty`, `lineBreak`, `macro`, `fieldCount`,
/// `unknownLine`).
class CronEditError implements FrbException {
  final String code;

  const CronEditError({required this.code});

  @override
  int get hashCode => code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronEditError &&
          runtimeType == other.runtimeType &&
          code == other.code;
}

/// A listing or a save the machine refused.
class CronFfiError implements FrbException {
  /// `crontab` is not installed at all.
  final bool notInstalled;

  /// What the machine said, or why its output was not read.
  final String? detail;

  const CronFfiError({required this.notInstalled, this.detail});

  @override
  int get hashCode => notInstalled.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronFfiError &&
          runtimeType == other.runtimeType &&
          notInstalled == other.notInstalled &&
          detail == other.detail;
}

/// One job in a document. `line_index` is what an edit names it by.
class CronJobLine {
  final int lineIndex;
  final String schedule;
  final String command;
  final bool enabled;

  const CronJobLine({
    required this.lineIndex,
    required this.schedule,
    required this.command,
    required this.enabled,
  });

  @override
  int get hashCode =>
      lineIndex.hashCode ^
      schedule.hashCode ^
      command.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronJobLine &&
          runtimeType == other.runtimeType &&
          lineIndex == other.lineIndex &&
          schedule == other.schedule &&
          command == other.command &&
          enabled == other.enabled;
}

class CronListing {
  final String user;
  final CronDocumentData document;

  /// `None` when the server's `date` could not say.
  final CronServerClock? clock;

  const CronListing({required this.user, required this.document, this.clock});

  @override
  int get hashCode => user.hashCode ^ document.hashCode ^ clock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronListing &&
          runtimeType == other.runtimeType &&
          user == other.user &&
          document == other.document &&
          clock == other.clock;
}

/// An expression expanded. Day of week counts Sunday as `0`.
class CronScheduleFields {
  final Uint32List minutes;
  final Uint32List hours;
  final Uint32List daysOfMonth;
  final Uint32List months;
  final Uint32List daysOfWeek;
  final bool dayOfMonthRestricted;
  final bool dayOfWeekRestricted;
  final bool isReboot;

  const CronScheduleFields({
    required this.minutes,
    required this.hours,
    required this.daysOfMonth,
    required this.months,
    required this.daysOfWeek,
    required this.dayOfMonthRestricted,
    required this.dayOfWeekRestricted,
    required this.isReboot,
  });

  @override
  int get hashCode =>
      minutes.hashCode ^
      hours.hashCode ^
      daysOfMonth.hashCode ^
      months.hashCode ^
      daysOfWeek.hashCode ^
      dayOfMonthRestricted.hashCode ^
      dayOfWeekRestricted.hashCode ^
      isReboot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronScheduleFields &&
          runtimeType == other.runtimeType &&
          minutes == other.minutes &&
          hours == other.hours &&
          daysOfMonth == other.daysOfMonth &&
          months == other.months &&
          daysOfWeek == other.daysOfWeek &&
          dayOfMonthRestricted == other.dayOfMonthRestricted &&
          dayOfWeekRestricted == other.dayOfWeekRestricted &&
          isReboot == other.isReboot;
}

/// What the server's `date +'%s %z'` said when the listing was read.
class CronServerClock {
  final PlatformInt64 epochSeconds;

  /// Minutes east of UTC.
  final int offsetMinutes;

  const CronServerClock({
    required this.epochSeconds,
    required this.offsetMinutes,
  });

  @override
  int get hashCode => epochSeconds.hashCode ^ offsetMinutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronServerClock &&
          runtimeType == other.runtimeType &&
          epochSeconds == other.epochSeconds &&
          offsetMinutes == other.offsetMinutes;
}

/// A time on the server's wall clock, the fields a crontab line is written in.
class CronWall {
  final int year;
  final int month;
  final int day;
  final int hour;
  final int minute;

  const CronWall({
    required this.year,
    required this.month,
    required this.day,
    required this.hour,
    required this.minute,
  });

  @override
  int get hashCode =>
      year.hashCode ^
      month.hashCode ^
      day.hashCode ^
      hour.hashCode ^
      minute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CronWall &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          month == other.month &&
          day == other.day &&
          hour == other.hour &&
          minute == other.minute;
}
