// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

String filesListCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesListCommand(path: path);

String filesStatCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesStatCommand(path: path);

/// `(mark, exit code)` for "nothing there" and for "could not look".
FilesStatMarkers filesStatMarkers() =>
    RustLib.instance.api.crateApiFilesFilesStatMarkers();

/// `Err` is output that is not a listing: cut short, or not this command's.
List<ShellFileRecord> filesParseRecords({required String output}) =>
    RustLib.instance.api.crateApiFilesFilesParseRecords(output: output);

String filesRenameCommand({required String from, required String to}) =>
    RustLib.instance.api.crateApiFilesFilesRenameCommand(from: from, to: to);

String filesMkdirCommand({required String path, required bool parents}) =>
    RustLib.instance.api.crateApiFilesFilesMkdirCommand(
      path: path,
      parents: parents,
    );

/// `is_dir` is what a stat said, `None` where it could not be asked.
String filesRemoveCommand({
  required String path,
  bool? isDir,
  required bool recursive,
  required bool force,
}) => RustLib.instance.api.crateApiFilesFilesRemoveCommand(
  path: path,
  isDir: isDir,
  recursive: recursive,
  force: force,
);

String filesChmodCommand({required String path, required int mode}) =>
    RustLib.instance.api.crateApiFilesFilesChmodCommand(path: path, mode: mode);

String filesSizeCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesSizeCommand(path: path);

PlatformInt64? filesParseSize({required String output}) =>
    RustLib.instance.api.crateApiFilesFilesParseSize(output: output);

String filesReadCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesReadCommand(path: path);

String filesWriteBase64Command({required String data, required String path}) =>
    RustLib.instance.api.crateApiFilesFilesWriteBase64Command(
      data: data,
      path: path,
    );

/// `inner` as root, the password on `sudo -S`'s stdin. Sent to a shell over
/// stdin, never as a process argument.
String filesSudoCommand({required String inner, required String password}) =>
    RustLib.instance.api.crateApiFilesFilesSudoCommand(
      inner: inner,
      password: password,
    );

String filesHomeCommand({required String user}) =>
    RustLib.instance.api.crateApiFilesFilesHomeCommand(user: user);

/// The home directory `passwd` names, else the usual one for `user`.
String filesHomeFrom({String? output, required String user}) =>
    RustLib.instance.api.crateApiFilesFilesHomeFrom(output: output, user: user);

String filesWritableCommand({required String dir}) =>
    RustLib.instance.api.crateApiFilesFilesWritableCommand(dir: dir);

String filesInDirCommand({required String dir, required String command}) =>
    RustLib.instance.api.crateApiFilesFilesInDirCommand(
      dir: dir,
      command: command,
    );

String filesEditorCommand({
  required String editor,
  required String path,
  required bool sudo,
}) => RustLib.instance.api.crateApiFilesFilesEditorCommand(
  editor: editor,
  path: path,
  sudo: sudo,
);

/// `None` for a file this does not know how to unpack.
String? filesExtractCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesExtractCommand(path: path);

String filesScpSourceCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesScpSourceCommand(path: path);

String filesScpSinkCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesScpSinkCommand(path: path);

/// `(is a directory, nothing there)` exit codes of [`files_capped_read_command`].
Int32List filesCappedReadExits() =>
    RustLib.instance.api.crateApiFilesFilesCappedReadExits();

String filesCappedReadCommand({required String path, required int maxBytes}) =>
    RustLib.instance.api.crateApiFilesFilesCappedReadCommand(
      path: path,
      maxBytes: maxBytes,
    );

/// `Err` is output that is not this command's.
CappedRead filesParseCappedRead({
  required String output,
  required int maxBytes,
}) => RustLib.instance.api.crateApiFilesFilesParseCappedRead(
  output: output,
  maxBytes: maxBytes,
);

/// Replaces `path` with the base64 on stdin, staged in an exclusive temp file.
String filesAtomicWriteCommand({required String path}) =>
    RustLib.instance.api.crateApiFilesFilesAtomicWriteCommand(path: path);

/// What [`files_capped_read_command`] answered.
class CappedRead {
  /// The whole file's size, which may exceed `data`.
  final PlatformInt64 size;
  final Uint8List data;

  const CappedRead({required this.size, required this.data});

  @override
  int get hashCode => size.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CappedRead &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          data == other.data;
}

class FilesStatMarkers {
  final String absentMark;
  final int absentExit;
  final String deniedMark;
  final int deniedExit;

  const FilesStatMarkers({
    required this.absentMark,
    required this.absentExit,
    required this.deniedMark,
    required this.deniedExit,
  });

  @override
  int get hashCode =>
      absentMark.hashCode ^
      absentExit.hashCode ^
      deniedMark.hashCode ^
      deniedExit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilesStatMarkers &&
          runtimeType == other.runtimeType &&
          absentMark == other.absentMark &&
          absentExit == other.absentExit &&
          deniedMark == other.deniedMark &&
          deniedExit == other.deniedExit;
}

/// One entry of a listing. `kind` is `dir`, `link`, `file` or `other`.
class ShellFileRecord {
  final String name;
  final String kind;
  final PlatformInt64? size;

  /// Seconds since the epoch.
  final PlatformInt64? mtime;
  final int? mode;

  const ShellFileRecord({
    required this.name,
    required this.kind,
    this.size,
    this.mtime,
    this.mode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      kind.hashCode ^
      size.hashCode ^
      mtime.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShellFileRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          size == other.size &&
          mtime == other.mtime &&
          mode == other.mode;
}
