// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

/// Which firewalls the server has, and how the app reaches it; for `sh`,
/// never as root.
String firewallProbeScript() =>
    RustLib.instance.api.crateApiFirewallFirewallProbeScript();

FirewallProbeResult firewallParseProbe({required String output}) =>
    RustLib.instance.api.crateApiFirewallFirewallParseProbe(output: output);

/// The firewall to show first.
FirewallKind? firewallPreferred({required FirewallProbeResult probe}) =>
    RustLib.instance.api.crateApiFirewallFirewallPreferred(probe: probe);

/// `commands` as one script, stopping at the first that fails, never
/// exiting 2.
String firewallScript({required List<String> commands}) =>
    RustLib.instance.api.crateApiFirewallFirewallScript(commands: commands);

bool firewallReachAdmits({required FirewallReach reach}) =>
    RustLib.instance.api.crateApiFirewallFirewallReachAdmits(reach: reach);

/// Whether `after` is a change for the worse from `before`.
bool firewallReachWorseThan({
  required FirewallReach after,
  required FirewallReach before,
}) => RustLib.instance.api.crateApiFirewallFirewallReachWorseThan(
  after: after,
  before: before,
);

String ufwReadScript() => RustLib.instance.api.crateApiFirewallUfwReadScript();

UfwSnapshot ufwParse({required String output}) =>
    RustLib.instance.api.crateApiFirewallUfwParse(output: output);

/// Whether a new connection like `access` gets through; `active`, `rules`
/// and `incoming` stand in for the snapshot's own.
FirewallReach ufwReach({
  required UfwSnapshot snapshot,
  required FirewallAccess access,
  bool? active,
  List<UfwRule>? rules,
  UfwPolicy? incoming,
}) => RustLib.instance.api.crateApiFirewallUfwReach(
  snapshot: snapshot,
  access: access,
  active: active,
  rules: rules,
  incoming: incoming,
);

/// The snapshot's rules with `added` first, or last.
List<UfwRule> ufwWithRules({
  required UfwSnapshot snapshot,
  required List<UfwRule> added,
  required bool prepend,
}) => RustLib.instance.api.crateApiFirewallUfwWithRules(
  snapshot: snapshot,
  added: added,
  prepend: prepend,
);

/// The rules ufw would add for `draft`, with `apps` resolving a profile.
List<UfwRule> ufwDraftRules({
  required UfwRuleDraft draft,
  required List<UfwApp> apps,
}) => RustLib.instance.api.crateApiFirewallUfwDraftRules(
  draft: draft,
  apps: apps,
);

UfwDraftIssue? ufwValidateDraft({required UfwRuleDraft draft}) =>
    RustLib.instance.api.crateApiFirewallUfwValidateDraft(draft: draft);

/// The command adding `draft`; an error names the issue
/// [`ufw_validate_draft`] would have.
String ufwAddCommand({required UfwRuleDraft draft}) =>
    RustLib.instance.api.crateApiFirewallUfwAddCommand(draft: draft);

List<String> ufwDeleteCommands({required UfwRule rule}) =>
    RustLib.instance.api.crateApiFirewallUfwDeleteCommands(rule: rule);

String ufwEnableCommand() =>
    RustLib.instance.api.crateApiFirewallUfwEnableCommand();

String ufwDisableCommand() =>
    RustLib.instance.api.crateApiFirewallUfwDisableCommand();

String ufwReloadCommand() =>
    RustLib.instance.api.crateApiFirewallUfwReloadCommand();

String ufwPolicyCommand({required UfwChain chain, required UfwPolicy policy}) =>
    RustLib.instance.api.crateApiFirewallUfwPolicyCommand(
      chain: chain,
      policy: policy,
    );

String ufwLoggingCommand({required UfwLogLevel level}) =>
    RustLib.instance.api.crateApiFirewallUfwLoggingCommand(level: level);

/// Lets TCP in to `port`, before every other rule.
String ufwAllowTcpCommand({required int port}) =>
    RustLib.instance.api.crateApiFirewallUfwAllowTcpCommand(port: port);

/// `in`, `out`: the word ufw writes.
String ufwDirectionToken({required UfwDirection direction}) => RustLib
    .instance
    .api
    .crateApiFirewallUfwDirectionToken(direction: direction);

/// `log`, `log-all`: the word ufw writes.
String ufwLogToken({required UfwLog log}) =>
    RustLib.instance.api.crateApiFirewallUfwLogToken(log: log);

String firewalldReadScript() =>
    RustLib.instance.api.crateApiFirewallFirewalldReadScript();

FirewalldSnapshot firewalldParse({required String output}) =>
    RustLib.instance.api.crateApiFirewallFirewalldParse(output: output);

/// What is in force: the runtime while running, else the permanent.
List<FirewalldZone> firewalldZones({required FirewalldSnapshot snapshot}) =>
    RustLib.instance.api.crateApiFirewallFirewalldZones(snapshot: snapshot);

bool firewalldDrifted({required FirewalldSnapshot snapshot}) =>
    RustLib.instance.api.crateApiFirewallFirewalldDrifted(snapshot: snapshot);

/// The zones a connection like `access` may be handled by; `zones` and
/// `default_zone` stand in for the snapshot's own.
List<FirewalldZone> firewalldZonesFor({
  required FirewalldSnapshot snapshot,
  required FirewallAccess access,
  String? iface,
  List<FirewalldZone>? zones,
  String? defaultZone,
}) => RustLib.instance.api.crateApiFirewallFirewalldZonesFor(
  snapshot: snapshot,
  access: access,
  iface: iface,
  zones: zones,
  defaultZone: defaultZone,
);

/// Whether a new connection like `access` gets through; `running`, `panic`,
/// `zones` and `default_zone` stand in for the snapshot's own.
FirewallReach firewalldReach({
  required FirewalldSnapshot snapshot,
  required FirewallAccess access,
  String? iface,
  bool? running,
  bool? panic,
  List<FirewalldZone>? zones,
  String? defaultZone,
}) => RustLib.instance.api.crateApiFirewallFirewalldReach(
  snapshot: snapshot,
  access: access,
  iface: iface,
  running: running,
  panic: panic,
  zones: zones,
  defaultZone: defaultZone,
);

FirewalldRichRule firewalldParseRichRule({required String raw}) =>
    RustLib.instance.api.crateApiFirewallFirewalldParseRichRule(raw: raw);

/// `8080/tcp`, as firewalld writes a port and takes it back.
String firewalldPortSpec({required FirewalldPort port}) =>
    RustLib.instance.api.crateApiFirewallFirewalldPortSpec(port: port);

/// What `--set-target` takes: `%%REJECT%%` for `REJECT`.
String firewalldTargetToken({required FirewalldTarget target}) =>
    RustLib.instance.api.crateApiFirewallFirewalldTargetToken(target: target);

/// Adds `value` to `zone`, or removes it; both configurations while
/// `running`.
List<String> firewalldItemCommands({
  required bool running,
  required String zone,
  required FirewalldItem item,
  required String value,
  required bool add,
}) => RustLib.instance.api.crateApiFirewallFirewalldItemCommands(
  running: running,
  zone: zone,
  item: item,
  value: value,
  add: add,
);

List<String> firewalldPortCommands({
  required bool running,
  required String zone,
  required FirewalldPort port,
  required bool add,
}) => RustLib.instance.api.crateApiFirewallFirewalldPortCommands(
  running: running,
  zone: zone,
  port: port,
  add: add,
);

/// A rich rule letting TCP in to `port` before anything in its zone.
String firewalldKeepOpenRule({required int port}) =>
    RustLib.instance.api.crateApiFirewallFirewalldKeepOpenRule(port: port);

List<String> firewalldChangeInterface({
  required bool running,
  required String zone,
  required String iface,
}) => RustLib.instance.api.crateApiFirewallFirewalldChangeInterface(
  running: running,
  zone: zone,
  iface: iface,
);

List<String> firewalldRemoveInterface({
  required bool running,
  required String zone,
  required String iface,
}) => RustLib.instance.api.crateApiFirewallFirewalldRemoveInterface(
  running: running,
  zone: zone,
  iface: iface,
);

List<String> firewalldMasquerade({
  required bool running,
  required String zone,
  required bool add,
}) => RustLib.instance.api.crateApiFirewallFirewalldMasquerade(
  running: running,
  zone: zone,
  add: add,
);

List<String> firewalldTarget({
  required bool running,
  required String zone,
  required FirewalldTarget target,
}) => RustLib.instance.api.crateApiFirewallFirewalldTarget(
  running: running,
  zone: zone,
  target: target,
);

String firewalldDefaultZone({required bool running, required String zone}) =>
    RustLib.instance.api.crateApiFirewallFirewalldDefaultZone(
      running: running,
      zone: zone,
    );

String firewalldReloadCommand() =>
    RustLib.instance.api.crateApiFirewallFirewalldReloadCommand();

String firewalldRuntimeToPermanentCommand() =>
    RustLib.instance.api.crateApiFirewallFirewalldRuntimeToPermanentCommand();

String firewalldPanicOffCommand() =>
    RustLib.instance.api.crateApiFirewallFirewalldPanicOffCommand();

String firewalldStartCommand() =>
    RustLib.instance.api.crateApiFirewallFirewalldStartCommand();

String firewalldStopCommand() =>
    RustLib.instance.api.crateApiFirewallFirewalldStopCommand();

/// A typed port as firewalld writes it, or None.
FirewalldPort? firewalldParsePort({required String value}) =>
    RustLib.instance.api.crateApiFirewallFirewalldParsePort(value: value);

FirewalldInputIssue? firewalldCheckSource({required String value}) =>
    RustLib.instance.api.crateApiFirewallFirewalldCheckSource(value: value);

FirewalldInputIssue? firewalldCheckInterface({required String value}) =>
    RustLib.instance.api.crateApiFirewallFirewalldCheckInterface(value: value);

FirewalldInputIssue? firewalldCheckRichRule({required String value}) =>
    RustLib.instance.api.crateApiFirewallFirewalldCheckRichRule(value: value);

FirewalldInputIssue? firewalldCheckForwardPort({required String value}) =>
    RustLib.instance.api.crateApiFirewallFirewalldCheckForwardPort(
      value: value,
    );

class FirewallAccess {
  final FirewallAccessVia via;
  final int port;
  final String? client;
  final String? server;

  const FirewallAccess({
    required this.via,
    required this.port,
    this.client,
    this.server,
  });

  @override
  int get hashCode =>
      via.hashCode ^ port.hashCode ^ client.hashCode ^ server.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewallAccess &&
          runtimeType == other.runtimeType &&
          via == other.via &&
          port == other.port &&
          client == other.client &&
          server == other.server;
}

enum FirewallAccessVia { ssh, monitor }

enum FirewallKind { ufw, firewalld }

class FirewallProbeResult {
  final bool? ufw;
  final bool? firewalld;
  final bool root;
  final FirewallAccess? ssh;
  final String? sshInterface;

  const FirewallProbeResult({
    this.ufw,
    this.firewalld,
    required this.root,
    this.ssh,
    this.sshInterface,
  });

  @override
  int get hashCode =>
      ufw.hashCode ^
      firewalld.hashCode ^
      root.hashCode ^
      ssh.hashCode ^
      sshInterface.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewallProbeResult &&
          runtimeType == other.runtimeType &&
          ufw == other.ufw &&
          firewalld == other.firewalld &&
          root == other.root &&
          ssh == other.ssh &&
          sshInterface == other.sshInterface;
}

enum FirewallReach { open, limited, unknown, blocked }

enum FirewalldInputIssue {
  invalidPort,
  invalidSource,
  invalidInterface,
  invalidRichRule,
  invalidForwardPort,
}

enum FirewalldItem { service, port, richRule, source, forwardPort }

class FirewalldPolicy {
  final String name;
  final String target;
  final bool egressHost;
  final bool decides;

  const FirewalldPolicy({
    required this.name,
    required this.target,
    required this.egressHost,
    required this.decides,
  });

  @override
  int get hashCode =>
      name.hashCode ^ target.hashCode ^ egressHost.hashCode ^ decides.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewalldPolicy &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          target == other.target &&
          egressHost == other.egressHost &&
          decides == other.decides;
}

class FirewalldPort {
  final String port;
  final String protocol;

  const FirewalldPort({required this.port, required this.protocol});

  @override
  int get hashCode => port.hashCode ^ protocol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewalldPort &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          protocol == other.protocol;
}

class FirewalldRichRule {
  final String raw;
  final int priority;
  final String? family;
  final String? source;
  final bool sourceNot;
  final bool sourceOther;
  final String? destination;
  final bool destinationNot;
  final String? element;
  final String? service;
  final String? port;
  final String? protocol;
  final String? action;
  final bool limited;

  const FirewalldRichRule({
    required this.raw,
    required this.priority,
    this.family,
    this.source,
    required this.sourceNot,
    required this.sourceOther,
    this.destination,
    required this.destinationNot,
    this.element,
    this.service,
    this.port,
    this.protocol,
    this.action,
    required this.limited,
  });

  @override
  int get hashCode =>
      raw.hashCode ^
      priority.hashCode ^
      family.hashCode ^
      source.hashCode ^
      sourceNot.hashCode ^
      sourceOther.hashCode ^
      destination.hashCode ^
      destinationNot.hashCode ^
      element.hashCode ^
      service.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      action.hashCode ^
      limited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewalldRichRule &&
          runtimeType == other.runtimeType &&
          raw == other.raw &&
          priority == other.priority &&
          family == other.family &&
          source == other.source &&
          sourceNot == other.sourceNot &&
          sourceOther == other.sourceOther &&
          destination == other.destination &&
          destinationNot == other.destinationNot &&
          element == other.element &&
          service == other.service &&
          port == other.port &&
          protocol == other.protocol &&
          action == other.action &&
          limited == other.limited;
}

class FirewalldSnapshot {
  final bool running;
  final String? version;
  final String? defaultZone;
  final bool panic;
  final List<FirewalldZone>? runtime;
  final List<FirewalldZone> permanent;
  final Map<String, List<FirewalldPort>> services;
  final List<String> serviceNames;
  final List<FirewalldPolicy> policies;

  const FirewalldSnapshot({
    required this.running,
    this.version,
    this.defaultZone,
    required this.panic,
    this.runtime,
    required this.permanent,
    required this.services,
    required this.serviceNames,
    required this.policies,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      version.hashCode ^
      defaultZone.hashCode ^
      panic.hashCode ^
      runtime.hashCode ^
      permanent.hashCode ^
      services.hashCode ^
      serviceNames.hashCode ^
      policies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewalldSnapshot &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          version == other.version &&
          defaultZone == other.defaultZone &&
          panic == other.panic &&
          runtime == other.runtime &&
          permanent == other.permanent &&
          services == other.services &&
          serviceNames == other.serviceNames &&
          policies == other.policies;
}

enum FirewalldTarget { defaultTarget, accept, drop, reject }

class FirewalldZone {
  final String name;
  final FirewalldTarget target;
  final bool active;
  final List<String> interfaces;
  final List<String> sources;
  final List<String> services;
  final List<FirewalldPort> ports;
  final List<String> protocols;
  final List<FirewalldPort> sourcePorts;
  final List<String> forwardPorts;
  final List<FirewalldRichRule> richRules;
  final bool masquerade;

  const FirewalldZone({
    required this.name,
    required this.target,
    required this.active,
    required this.interfaces,
    required this.sources,
    required this.services,
    required this.ports,
    required this.protocols,
    required this.sourcePorts,
    required this.forwardPorts,
    required this.richRules,
    required this.masquerade,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      target.hashCode ^
      active.hashCode ^
      interfaces.hashCode ^
      sources.hashCode ^
      services.hashCode ^
      ports.hashCode ^
      protocols.hashCode ^
      sourcePorts.hashCode ^
      forwardPorts.hashCode ^
      richRules.hashCode ^
      masquerade.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FirewalldZone &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          target == other.target &&
          active == other.active &&
          interfaces == other.interfaces &&
          sources == other.sources &&
          services == other.services &&
          ports == other.ports &&
          protocols == other.protocols &&
          sourcePorts == other.sourcePorts &&
          forwardPorts == other.forwardPorts &&
          richRules == other.richRules &&
          masquerade == other.masquerade;
}

enum UfwAction { allow, deny, reject, limit }

class UfwApp {
  final String name;
  final List<UfwAppPort> ports;

  const UfwApp({required this.name, required this.ports});

  @override
  int get hashCode => name.hashCode ^ ports.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwApp &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ports == other.ports;
}

class UfwAppPort {
  final String port;
  final String? protocol;

  const UfwAppPort({required this.port, this.protocol});

  @override
  int get hashCode => port.hashCode ^ protocol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwAppPort &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          protocol == other.protocol;
}

enum UfwChain { incoming, outgoing, routed }

enum UfwDirection { incoming, outgoing }

enum UfwDraftIssue {
  nothingMatched,
  invalidPort,
  tooManyPorts,
  portsNeedProtocol,
  invalidAddress,
  mixedIpVersions,
  invalidInterface,
  invalidComment,
  invalidProtocol,
}

class UfwEndpoint {
  final String? address;
  final String? port;
  final String? app;

  const UfwEndpoint({this.address, this.port, this.app});

  @override
  int get hashCode => address.hashCode ^ port.hashCode ^ app.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwEndpoint &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          app == other.app;
}

enum UfwIpVersion { v4, v6, both }

enum UfwLog { log, logAll }

enum UfwLogLevel { off, low, medium, high, full }

enum UfwPolicy { allow, deny, reject }

class UfwRule {
  final UfwAction action;
  final UfwDirection direction;
  final bool routed;
  final UfwLog? log;
  final String? protocol;
  final UfwEndpoint to;
  final UfwEndpoint from;
  final String? interfaceIn;
  final String? interfaceOut;
  final String? comment;
  final UfwIpVersion ipVersion;
  final List<String> tuples;

  const UfwRule({
    required this.action,
    required this.direction,
    required this.routed,
    this.log,
    this.protocol,
    required this.to,
    required this.from,
    this.interfaceIn,
    this.interfaceOut,
    this.comment,
    required this.ipVersion,
    required this.tuples,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      direction.hashCode ^
      routed.hashCode ^
      log.hashCode ^
      protocol.hashCode ^
      to.hashCode ^
      from.hashCode ^
      interfaceIn.hashCode ^
      interfaceOut.hashCode ^
      comment.hashCode ^
      ipVersion.hashCode ^
      tuples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwRule &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          direction == other.direction &&
          routed == other.routed &&
          log == other.log &&
          protocol == other.protocol &&
          to == other.to &&
          from == other.from &&
          interfaceIn == other.interfaceIn &&
          interfaceOut == other.interfaceOut &&
          comment == other.comment &&
          ipVersion == other.ipVersion &&
          tuples == other.tuples;
}

class UfwRuleDraft {
  final UfwAction action;
  final UfwDirection direction;
  final bool routed;
  final String? protocol;
  final String port;
  final String sourcePort;
  final String? app;
  final String from;
  final String to;
  final String interfaceIn;
  final String interfaceOut;
  final UfwLog? log;
  final String comment;
  final bool prepend;

  const UfwRuleDraft({
    required this.action,
    required this.direction,
    required this.routed,
    this.protocol,
    required this.port,
    required this.sourcePort,
    this.app,
    required this.from,
    required this.to,
    required this.interfaceIn,
    required this.interfaceOut,
    this.log,
    required this.comment,
    required this.prepend,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      direction.hashCode ^
      routed.hashCode ^
      protocol.hashCode ^
      port.hashCode ^
      sourcePort.hashCode ^
      app.hashCode ^
      from.hashCode ^
      to.hashCode ^
      interfaceIn.hashCode ^
      interfaceOut.hashCode ^
      log.hashCode ^
      comment.hashCode ^
      prepend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwRuleDraft &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          direction == other.direction &&
          routed == other.routed &&
          protocol == other.protocol &&
          port == other.port &&
          sourcePort == other.sourcePort &&
          app == other.app &&
          from == other.from &&
          to == other.to &&
          interfaceIn == other.interfaceIn &&
          interfaceOut == other.interfaceOut &&
          log == other.log &&
          comment == other.comment &&
          prepend == other.prepend;
}

class UfwSnapshot {
  final bool? active;
  final String? statusLine;
  final String? version;
  final UfwLogLevel? logLevel;
  final bool ipv6;
  final Map<UfwChain, UfwPolicy> policies;
  final List<UfwRule> rules;
  final List<UfwApp> apps;

  const UfwSnapshot({
    this.active,
    this.statusLine,
    this.version,
    this.logLevel,
    required this.ipv6,
    required this.policies,
    required this.rules,
    required this.apps,
  });

  @override
  int get hashCode =>
      active.hashCode ^
      statusLine.hashCode ^
      version.hashCode ^
      logLevel.hashCode ^
      ipv6.hashCode ^
      policies.hashCode ^
      rules.hashCode ^
      apps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UfwSnapshot &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          statusLine == other.statusLine &&
          version == other.version &&
          logLevel == other.logLevel &&
          ipv6 == other.ipv6 &&
          policies == other.policies &&
          rules == other.rules &&
          apps == other.apps;
}
