// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

/// The canonical host for `iperf`, or `None` if it is not one.
String? iperfNormalizeHost({required String raw}) =>
    RustLib.instance.api.crateApiIperfIperfNormalizeHost(raw: raw);

/// The port as a number, or `None` if it is not one.
int? iperfValidPort({required String raw}) =>
    RustLib.instance.api.crateApiIperfIperfValidPort(raw: raw);

/// `iperf -c <host> -p <port>`. The host is validated again here, so a caller
/// cannot reach a command line by skipping [`iperf_normalize_host`].
String iperfClientCommand({required String host, required int port}) => RustLib
    .instance
    .api
    .crateApiIperfIperfClientCommand(host: host, port: port);
