// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_system_or_err`, `parse_system`

/// Parse all output of one collection round, returning `ServerStatus` JSON.
/// `system`: "linux" | "bsd" | "windows"; see `ParseOptions` for `temp_divisor`.
/// Async: runs on the Rust thread pool without blocking the UI isolate
Future<String> parseStatusJson({
  required String system,
  required Map<String, String> raw,
  required double tempDivisor,
}) => RustLib.instance.api.crateApiParserParseStatusJson(
  system: system,
  raw: raw,
  tempDivisor: tempDivisor,
);

/// Windows WMI double-sample net speed delta, returning `[{name, rx, tx}]` JSON (bytes/sec)
String parseWindowsNetSpeedJson({required String raw}) =>
    RustLib.instance.api.crateApiParserParseWindowsNetSpeedJson(raw: raw);

/// Per-platform collection command manifest (the app's script generation derives from it, versioned with the parsers)
List<CommandSpec> commandSpecs({required String system}) =>
    RustLib.instance.api.crateApiParserCommandSpecs(system: system);

/// Collection command, single source of truth shared with the app's script generation
class CommandSpec {
  final String key;
  final String cmd;

  const CommandSpec({required this.key, required this.cmd});

  @override
  int get hashCode => key.hashCode ^ cmd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandSpec &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          cmd == other.cmd;
}
