// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Reads a manifest without loading anything.
///
/// What the install page needs: the name, the version, and the permissions to
/// put in front of the user. Refuses a manifest asking for an ABI this build
/// does not implement, which is the check that keeps a newer plugin from
/// half-working.
PluginManifestInfo pluginReadManifest({required String manifestJson}) => RustLib
    .instance
    .api
    .crateApiPluginPluginReadManifest(manifestJson: manifestJson);

/// The ABI this build implements. A plugin whose manifest asks for more is
/// refused.
int pluginAbiVersion() => RustLib.instance.api.crateApiPluginPluginAbiVersion();

/// Every permission a manifest may ask for, so the app's dialog and this build
/// cannot disagree about the list.
List<String> pluginPermissions() =>
    RustLib.instance.api.crateApiPluginPluginPermissions();

/// Every function a plugin may call, as `sb.http.fetch` and so on.
///
/// The app implements these; reading the list from here is what keeps the two
/// from drifting.
List<String> pluginHostFunctions() =>
    RustLib.instance.api.crateApiPluginPluginHostFunctions();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginRuntime>>
abstract class PluginRuntime implements RustOpaqueInterface {
  /// The app's answer to one [`PluginRequest`].
  ///
  /// Exactly one of the three outcomes:
  ///
  /// - `ok` — the JSON the function answers with. `null` for the ones that
  ///   answer nothing.
  /// - `error_kind` plus `error_message` — the app tried and could not. The
  ///   plugin sees a rejected promise it can catch.
  /// - `denied` — the app refuses. The plugin cannot catch it, and the call
  ///   ends the way an ungranted function would.
  ///
  /// Answers whether anything was still waiting. `false` is ordinary: a page
  /// closed while a request was in flight.
  bool answer({
    required BigInt callId,
    String? ok,
    String? errorKind,
    String? errorMessage,
    String? denied,
  });

  /// Calls one of PLUGINS.md 4.2's exports.
  ///
  /// Not `sync`, and this is the one that would deadlock: it waits for the
  /// plugin, which waits for Dart to answer its host calls.
  Future<String> call({
    required BigInt instance,
    required String export_,
    required String input,
  });

  /// What the plugin exports, so the app can tell a card from a status plugin
  /// without calling anything.
  List<String> exports({required BigInt instance});

  bool hasExport({required BigInt instance, required String export_});

  /// Adds a server handle the app issued outside a call — after a picker, or
  /// when a surface is rebound.
  void issueServerHandle({required BigInt instance, required String handle});

  /// Compiles a plugin and keeps it on a thread of its own.
  ///
  /// Not `sync`: a module may await a host call while it loads, and that
  /// answer has to come from the Dart isolate.
  Future<BigInt> load({required PluginSpec spec});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Starts the runtime.
  ///
  /// Both sinks stay open for the runtime's life. A plugin blocks until its
  /// request is answered, so whatever reads `requests` must keep reading.
  static Future<PluginRuntime> newInstance({
    required RustStreamSink<PluginRequest> requests,
    required RustStreamSink<PluginLog> logs,
  }) => RustLib.instance.api.crateApiPluginPluginRuntimeNew(
    requests: requests,
    logs: logs,
  );

  /// How many requests the app has not answered. For diagnostics.
  int outstanding();

  /// What a status plugin wants run on `platform`. PLUGINS.md 9.
  ///
  /// Not `sync`, for [`PluginRuntime::call`]'s reason: a plugin may await a
  /// host call while answering.
  ///
  /// The same call the install page makes to show what the plugin will run,
  /// so what the user was shown and what the app runs cannot differ for want
  /// of asking twice.
  Future<PluginStatusCmd> statusCmd({
    required BigInt instance,
    required String platform,
  });

  /// Hands a status plugin what its command printed, and takes back the
  /// readings.
  ///
  /// Checked by `sbm_plugin::status` before it gets here: a label longer
  /// than a label is cut, a `percent` outside 0..1 is dropped rather than
  /// clamped, and only a document that is not this shape at all is refused.
  /// A bad status plugin costs a row, not a card.
  Future<PluginStatusResult> statusParse({
    required BigInt instance,
    required String text,
  });

  /// Ends an instance and waits for its thread, so its outstanding requests
  /// are cancelled before this returns.
  Future<void> unload({required BigInt instance});
}

/// A card on the server detail page, drawn from the widget tree the plugin
/// answers `open` with. PLUGINS.md 5.3.
///
/// Unlike a status contribution this has a surface: the plugin holds state,
/// answers events, and is ticked while it is on screen.
class PluginCardInfo {
  /// Stable within the plugin; the stored id is `<plugin id>:<this>`.
  final String id;
  final String label;
  final String? icon;
  final bool defaultOn;

  /// Show this only on a server that has configuration for the plugin.
  ///
  /// Not a nicety. A card that appeared on every server to say "not
  /// configured" would be a row of noise on the machines that have no BMC,
  /// which is most of them — and the plugin cannot decide it for itself,
  /// because deciding means being instantiated and instantiated is already
  /// the cost.
  final bool requiresConfig;

  const PluginCardInfo({
    required this.id,
    required this.label,
    this.icon,
    required this.defaultOn,
    required this.requiresConfig,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      icon.hashCode ^
      defaultOn.hashCode ^
      requiresConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginCardInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          icon == other.icon &&
          defaultOn == other.defaultOn &&
          requiresConfig == other.requiresConfig;
}

/// Why a plugin call did not answer.
///
/// A local type rather than the runtime's own enum: the app branches on one
/// thing — whether this was a refusal to put in front of the user or a fault to
/// log — and a string pair crosses the boundary without the generated code
/// needing to know the runtime's shape.
class PluginFailure implements FrbException {
  /// `module`, `manifest`, `no_such_export`, `threw`, `bad_answer`,
  /// `denied` or `internal`. `denied` names a permission and is the one to
  /// show; the rest belong in a log.
  final String kind;
  final String message;

  const PluginFailure({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// A line a plugin wrote through `sb.log.*`. Nothing answers it.
class PluginLog {
  final String pluginId;
  final String instanceId;

  /// `trace`, `debug`, `info`, `warn` or `error`.
  final String level;
  final String message;

  const PluginLog({
    required this.pluginId,
    required this.instanceId,
    required this.level,
    required this.message,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      instanceId.hashCode ^
      level.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginLog &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          instanceId == other.instanceId &&
          level == other.level &&
          message == other.message;
}

/// What the install page shows.
class PluginManifestInfo {
  final String id;
  final String version;
  final int abi;
  final String name;
  final String description;

  /// Permission names, for the dialog. PLUGINS.md 6.1.
  final List<String> permissions;

  /// Present when this plugin draws a card on the server detail page.
  final PluginCardInfo? card;

  /// Present when this plugin puts a button in the server function bar.
  final PluginPageInfo? page;

  /// Present when this plugin has a page of its own under Settings.
  final PluginSettingsInfo? settings;

  /// Present when this plugin contributes readings to the status page.
  final PluginStatusInfo? status;
  final String? license;
  final String? sourceUrl;

  const PluginManifestInfo({
    required this.id,
    required this.version,
    required this.abi,
    required this.name,
    required this.description,
    required this.permissions,
    this.card,
    this.page,
    this.settings,
    this.status,
    this.license,
    this.sourceUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      version.hashCode ^
      abi.hashCode ^
      name.hashCode ^
      description.hashCode ^
      permissions.hashCode ^
      card.hashCode ^
      page.hashCode ^
      settings.hashCode ^
      status.hashCode ^
      license.hashCode ^
      sourceUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginManifestInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          version == other.version &&
          abi == other.abi &&
          name == other.name &&
          description == other.description &&
          permissions == other.permissions &&
          card == other.card &&
          page == other.page &&
          settings == other.settings &&
          status == other.status &&
          license == other.license &&
          sourceUrl == other.sourceUrl;
}

/// A button in the server function bar, opening a page. PLUGINS.md 5.3.
class PluginPageInfo {
  /// Stable within the plugin; the stored id is `<plugin id>:<this>`.
  final String id;
  final String label;
  final String? icon;
  final bool defaultOn;

  /// What the server must be able to do for the button to appear —
  /// `shell`, `terminal`, `files`, `byte_stream`, `stored_history` or
  /// `persistent_session`.
  ///
  /// The app's own `availableWith` switch, moved into data. A button an
  /// entry cannot serve opens a page that can never load, and which of these
  /// a transport meets is the app's answer rather than the plugin's.
  final List<String> needs;

  /// See [`PluginCardInfo::requires_config`].
  final bool requiresConfig;

  const PluginPageInfo({
    required this.id,
    required this.label,
    this.icon,
    required this.defaultOn,
    required this.needs,
    required this.requiresConfig,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      icon.hashCode ^
      defaultOn.hashCode ^
      needs.hashCode ^
      requiresConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginPageInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          icon == other.icon &&
          defaultOn == other.defaultOn &&
          needs == other.needs &&
          requiresConfig == other.requiresConfig;
}

/// Something a plugin asked the app to do.
///
/// Answer it with [`PluginRuntime::answer`], quoting `call_id`. An answer that
/// never comes stalls that plugin until its own timeout, so answer every one —
/// including with a failure.
class PluginRequest {
  final BigInt callId;

  /// Which plugin, as its manifest `id`.
  final String pluginId;

  /// Which instance, as the app named it when loading.
  final String instanceId;

  /// `sb.http.fetch`, and so on. The full list is PLUGINS.md 4.3.
  final String func;

  /// The argument, as JSON.
  final String request;

  const PluginRequest({
    required this.callId,
    required this.pluginId,
    required this.instanceId,
    required this.func,
    required this.request,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      pluginId.hashCode ^
      instanceId.hashCode ^
      func.hashCode ^
      request.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginRequest &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          pluginId == other.pluginId &&
          instanceId == other.instanceId &&
          func == other.func &&
          request == other.request;
}

/// A plugin's own page under Settings. PLUGINS.md 5.3.
///
/// Not in any arrangement: a settings page is where a plugin is configured,
/// so hiding it behind a switch the user would have to find first is the one
/// thing it cannot afford. It appears while the plugin is installed and
/// enabled, and goes when it is not.
class PluginSettingsInfo {
  /// Stable within the plugin; the stored id is `<plugin id>:<this>`.
  final String id;
  final String label;
  final String? icon;

  const PluginSettingsInfo({required this.id, required this.label, this.icon});

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginSettingsInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          icon == other.icon;
}

/// Everything an instance needs beyond its source.
class PluginSpec {
  /// The manifest, verbatim. Parsed here so there is one parser.
  final String manifestJson;

  /// `plugin.js`.
  final String source;

  /// Unique per surface for as long as it is open.
  final String instanceId;

  /// Permissions the user agreed to, by name. Intersected with what the
  /// manifest asks for.
  final List<String> granted;

  /// This server's configuration for this plugin.
  final List<(String, String)> config;

  /// The opaque handle for the bound server, or absent for a global surface.
  final String? boundServer;

  const PluginSpec({
    required this.manifestJson,
    required this.source,
    required this.instanceId,
    required this.granted,
    required this.config,
    this.boundServer,
  });

  @override
  int get hashCode =>
      manifestJson.hashCode ^
      source.hashCode ^
      instanceId.hashCode ^
      granted.hashCode ^
      config.hashCode ^
      boundServer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginSpec &&
          runtimeType == other.runtimeType &&
          manifestJson == other.manifestJson &&
          source == other.source &&
          instanceId == other.instanceId &&
          granted == other.granted &&
          config == other.config &&
          boundServer == other.boundServer;
}

/// What a status plugin says to run.
class PluginStatusCmd {
  final String cmd;

  const PluginStatusCmd({required this.cmd});

  @override
  int get hashCode => cmd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginStatusCmd &&
          runtimeType == other.runtimeType &&
          cmd == other.cmd;
}

/// A status contribution, as the app needs it to decide what to collect.
///
/// PLUGINS.md 9. There is no surface: the app asks the plugin what to run,
/// runs it, hands back what it printed, and draws the readings with the
/// widgets it draws its own with.
class PluginStatusInfo {
  /// Stable within the plugin; the stored id is `<plugin id>:<this>`.
  final String id;
  final String label;
  final String? icon;
  final bool defaultOn;
  final bool requiresConfig;

  /// `linux`, `bsd`, `windows`. A plugin is not asked about a platform it
  /// did not name — the answer would be nothing, once per collection, or a
  /// command for the wrong system.
  final List<String> platforms;

  const PluginStatusInfo({
    required this.id,
    required this.label,
    this.icon,
    required this.defaultOn,
    required this.requiresConfig,
    required this.platforms,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      icon.hashCode ^
      defaultOn.hashCode ^
      requiresConfig.hashCode ^
      platforms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginStatusInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          icon == other.icon &&
          defaultOn == other.defaultOn &&
          requiresConfig == other.requiresConfig &&
          platforms == other.platforms;
}

/// One reading.
class PluginStatusItem {
  final String label;
  final String value;

  /// 0..1, drawn as a bar beside the value. Absent where the reading is not
  /// a proportion.
  final double? percent;

  /// `normal`, `muted`, `success`, `warning` or `danger` — a name rather
  /// than a colour, so a plugin's row looks like the app's own in both
  /// themes and cannot ship an unreadable one.
  final String tone;

  const PluginStatusItem({
    required this.label,
    required this.value,
    this.percent,
    required this.tone,
  });

  @override
  int get hashCode =>
      label.hashCode ^ value.hashCode ^ percent.hashCode ^ tone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginStatusItem &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          percent == other.percent &&
          tone == other.tone;
}

/// A status plugin's readings for one collection.
class PluginStatusResult {
  /// Falls back to the plugin's name when empty.
  final String title;
  final List<PluginStatusItem> items;

  /// Shown under the readings, for what a row cannot say.
  final String? note;

  const PluginStatusResult({
    required this.title,
    required this.items,
    this.note,
  });

  @override
  int get hashCode => title.hashCode ^ items.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginStatusResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          items == other.items &&
          note == other.note;
}
