// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `sort_mode`, `view_json`

/// What the process function printed → `PsView` JSON, ordered by `sort`
/// (`cpu`, `mem`, `rss`, `pid`, `user`, `name`, `read`, `write`) where the
/// table can answer it. `previous` is the last reading that parsed cleanly,
/// as this returned it; `sampled_at_millis` is when `raw` was produced.
Future<String> procViewJson({
  required String raw,
  required String system,
  String? sort,
  bool? ascending,
  String? previousJson,
  required PlatformInt64 sampledAtMillis,
}) => RustLib.instance.api.crateApiProcProcViewJson(
  raw: raw,
  system: system,
  sort: sort,
  ascending: ascending,
  previousJson: previousJson,
  sampledAtMillis: sampledAtMillis,
);

/// A reading [`proc_view_json`] returned, ordered again.
Future<String> procSortedJson({
  required String viewJsonIn,
  required String system,
  String? sort,
  bool? ascending,
}) => RustLib.instance.api.crateApiProcProcSortedJson(
  viewJsonIn: viewJsonIn,
  system: system,
  sort: sort,
  ascending: ascending,
);

/// The command that sends `signal` (`term`, `kill`) to `pid` once its start
/// identity is still `start_id`, or `None` where the platform cannot check
/// it. What it prints is read by [`proc_kill_outcome`].
String? procKillCommand({
  required PlatformInt64 pid,
  String? startId,
  required String system,
  required String signal,
}) => RustLib.instance.api.crateApiProcProcKillCommand(
  pid: pid,
  startId: startId,
  system: system,
  signal: signal,
);

/// What a stop printed: `succeeded`, `target_changed`, `denied` or `failed`.
String procKillOutcome({required String output}) =>
    RustLib.instance.api.crateApiProcProcKillOutcome(output: output);
