// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/api/bmc.dart';
import 'package:server_box/src/rust/api/virt.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `power_action`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Loopback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `dial`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// A guest's configuration (`/nodes/../config` JSON) read into
/// `sbm_virt::model::GuestDetail` JSON.
String pveGuestDetail({required String configJson, required bool lxc}) =>
    RustLib.instance.api.crateApiPvePveGuestDetail(
      configJson: configJson,
      lxc: lxc,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PveSession>>
abstract class PveSession implements RustOpaqueInterface {
  /// The headers that authenticate a connection made outside the session
  /// (a console's websocket, an upload), logging in first if needed.
  Future<List<PveHeader>> authHeaders();

  void close();

  /// Pins the certificate the last refused connection presented; answers
  /// the pin as stored.
  String confirmCert({required String fingerprint});

  /// A fresh console ticket.
  Future<PveConsoleTicket> console({
    required PveGuestRef guest,
    required PveConsoleKind kind,
  });

  /// `sbm_virt::model::GuestDetail` JSON.
  Future<String> detail({required PveGuestRef guest});

  /// `sbm_virt::model::Stats` JSON list, oldest first.
  Future<String> history({
    required PveGuestRef guest,
    required PveHistoryWindow window,
  });

  /// `sbm_virt::model::HostView` JSON.
  Future<String> load();

  /// Nothing is sent until the first call. `port` and `token` are the
  /// app's authenticated loopback tunnel to the API's address.
  factory PveSession({
    required PveLogin login,
    required int port,
    required List<int> token,
    required PveTiming timing,
  }) => RustLib.instance.api.crateApiPvePveSessionNew(
    login: login,
    port: port,
    token: token,
    timing: timing,
  );

  /// Runs `action` on `guest` and returns once PVE has finished it.
  Future<void> power({
    required PveGuestRef guest,
    required VirtActionKind action,
  });

  /// A request answered as the host answered it, for the app's calls that
  /// read PVE's answers themselves. `path` is the whole path, API root and
  /// query included. The session still logs in, renews, and replaces a
  /// refused ticket once.
  Future<PveRawResponse> raw({
    required PveMethod method,
    required String path,
    String? contentType,
    Uint8List? body,
  });

  /// Reads the guest's state again after an action made through
  /// [`PveSession::raw`] (a snapshot revert), so the next load shows it.
  Future<void> refreshStatus({required PveGuestRef guest});

  /// PVE's release, once a session has read it.
  String? release();

  /// Any API call in this session, `path` under `/api2/json` with its
  /// query: the body's `data` as JSON, or the whole body with `whole`.
  Future<String> request({
    required PveMethod method,
    required String path,
    String? contentType,
    Uint8List? body,
    required bool action,
    required bool whole,
  });

  /// Drops the session; the next call logs in again.
  void reset();

  /// A new tunnel to the same address. Connections still open on the old
  /// one fail and are made again.
  void setLoopback({required int port, required List<int> token});

  Future<void> submitTfa({required String code});

  /// Replaces the login (an edit, or a pin confirmed elsewhere). A new
  /// session starts when anything changed. An address change also needs a
  /// new tunnel: [`PveSession::set_loopback`].
  void updateLogin({required PveLogin login});

  /// Waits for the task `upid` on `node` to stop; its error is
  /// `actionFailed` with PVE's text.
  Future<void> waitTask({required String node, required String upid});
}

/// Which console (mirrors sbm_virt::model::ConsoleKind).
enum PveConsoleKind { text, vnc }

/// A PVE console ticket (mirrors sbm_virt::pve::client::PveConsole): fetch
/// right before connecting, a ticket is good for a short while and one use.
class PveConsoleTicket {
  final String node;
  final bool lxc;
  final int vmid;
  final bool vnc;
  final int port;

  /// Never logged.
  final String ticket;
  final String user;

  /// VNC: the password QEMU was given for this connection. Never logged.
  final String? password;

  /// `vncwebsocket`'s path and query, under the API's origin.
  final String websocketPath;

  const PveConsoleTicket({
    required this.node,
    required this.lxc,
    required this.vmid,
    required this.vnc,
    required this.port,
    required this.ticket,
    required this.user,
    this.password,
    required this.websocketPath,
  });

  @override
  int get hashCode =>
      node.hashCode ^
      lxc.hashCode ^
      vmid.hashCode ^
      vnc.hashCode ^
      port.hashCode ^
      ticket.hashCode ^
      user.hashCode ^
      password.hashCode ^
      websocketPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveConsoleTicket &&
          runtimeType == other.runtimeType &&
          node == other.node &&
          lxc == other.lxc &&
          vmid == other.vmid &&
          vnc == other.vnc &&
          port == other.port &&
          ticket == other.ticket &&
          user == other.user &&
          password == other.password &&
          websocketPath == other.websocketPath;
}

/// A PVE failure (mirrors sbm_virt::error::Error). `message` is the host's or
/// the transport's words, never a credential.
class PveError implements FrbException {
  final VirtFailure kind;
  final String? message;

  /// `sbm_virt::error::Detail` as JSON (`{"code": ..., ...}`).
  final String? detailJson;
  final CertInfo? cert;
  final String? previousFingerprint;

  /// The HTTP status the host answered with, when it was one.
  final int? status;

  const PveError({
    required this.kind,
    this.message,
    this.detailJson,
    this.cert,
    this.previousFingerprint,
    this.status,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      message.hashCode ^
      detailJson.hashCode ^
      cert.hashCode ^
      previousFingerprint.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          detailJson == other.detailJson &&
          cert == other.cert &&
          previousFingerprint == other.previousFingerprint &&
          status == other.status;
}

/// A guest as the app holds it, from the last load (mirrors the fields of
/// sbm_virt::model::Guest that a call on one guest reads).
class PveGuestRef {
  final String id;
  final String name;
  final String? node;
  final int? vmid;
  final bool lxc;

  /// What it offered at that load; an action not among these is refused.
  final List<VirtActionKind> actions;

  const PveGuestRef({
    required this.id,
    required this.name,
    this.node,
    this.vmid,
    required this.lxc,
    required this.actions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      node.hashCode ^
      vmid.hashCode ^
      lxc.hashCode ^
      actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveGuestRef &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          node == other.node &&
          vmid == other.vmid &&
          lxc == other.lxc &&
          actions == other.actions;
}

class PveHeader {
  final String name;
  final String value;

  const PveHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

/// How far back stored usage reaches (mirrors sbm_virt::model::HistoryWindow).
enum PveHistoryWindow { hour, day, week }

/// How a session logs in (mirrors sbm_virt::pve::Config). `token` picks the
/// API token; otherwise `user` and `password` log in, `password` being what
/// the app's `PveConfig.loginPassword` chose.
class PveLogin {
  final String addr;
  final bool token;
  final String user;
  final String password;
  final String tokenId;
  final String tokenSecret;
  final String? certSha256;

  const PveLogin({
    required this.addr,
    required this.token,
    required this.user,
    required this.password,
    required this.tokenId,
    required this.tokenSecret,
    this.certSha256,
  });

  @override
  int get hashCode =>
      addr.hashCode ^
      token.hashCode ^
      user.hashCode ^
      password.hashCode ^
      tokenId.hashCode ^
      tokenSecret.hashCode ^
      certSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveLogin &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          token == other.token &&
          user == other.user &&
          password == other.password &&
          tokenId == other.tokenId &&
          tokenSecret == other.tokenSecret &&
          certSha256 == other.certSha256;
}

enum PveMethod { get_, post, put, delete }

/// What [`PveSession::raw`] answered: the host's status and body as sent.
class PveRawResponse {
  final int status;
  final Uint8List body;

  const PveRawResponse({required this.status, required this.body});

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveRawResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}

/// How long a task is waited for, and how often it is asked about; `None`
/// keeps sbm_virt's defaults (1 s, 10 min).
class PveTiming {
  final BigInt? taskPollMs;
  final BigInt? taskTimeoutMs;

  const PveTiming({this.taskPollMs, this.taskTimeoutMs});

  @override
  int get hashCode => taskPollMs.hashCode ^ taskTimeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PveTiming &&
          runtimeType == other.runtimeType &&
          taskPollMs == other.taskPollMs &&
          taskTimeoutMs == other.taskTimeoutMs;
}

/// Why a host could not be read or an action did not happen (mirrors
/// sbm_virt::error::ErrorKind).
enum VirtFailure {
  unreachable,
  notConfigured,
  authFailed,
  needTfa,
  certUnconfirmed,
  certChanged,
  permissionDenied,
  invalidResponse,
  actionFailed,
  unsupported,
  exists,
  conflict,
  notInstalled,
  sudoPasswordRequired,
  sudoPasswordRejected,
  closed,
  unknown,
}
