// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:server_box/src/rust/frb_generated.dart';

part 'remote_desktop.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_vnc_event`, `bgra_to_rgba`, `certificate_event`, `classify_rdp_failure`, `copy_rect`, `draw_bgra`, `draw_jpeg`, `ensure_rect`, `event`, `finish_vnc_error`, `format_endpoint`, `format_sha256`, `frame_len`, `frame`, `handle_rdp_command`, `handle_vnc_command`, `is_ready`, `parse_sha256_fingerprint`, `publish_latest_frame`, `rdp_pixels_to_bgra`, `resize`, `run_rdp`, `run_vnc`, `send_rdp_fast_path`, `send_vnc_wheel`, `send`, `spawn`, `validate_endpoint`, `validate_size`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EventReceiver`, `EventSender`, `Frame`, `Framebuffer`, `RdpClipboardBackend`, `RdpClipboardState`, `SessionCommand`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_any_mut`, `as_any`, `assert_fields_are_eq`, `assert_fields_are_eq`, `client_capabilities`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `on_file_contents_request`, `on_file_contents_response`, `on_format_data_request`, `on_format_data_response`, `on_lock`, `on_process_negotiated_capabilities`, `on_ready`, `on_remote_copy`, `on_request_format_list`, `on_unlock`, `temporary_directory`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RemoteDesktopSessionHandle>>
abstract class RemoteDesktopSessionHandle implements RustOpaqueInterface {
  void close();

  /// Wait for the next state/input event or the newest complete frame.
  Future<RemoteDesktopEvent?> nextEvent();

  void releaseAllKeys();

  void resize({
    required int width,
    required int height,
    required int scaleFactor,
    int? physicalWidthMm,
    int? physicalHeightMm,
  });

  void sendClipboardText({required String text});

  void sendKey({required int code, required bool down, required bool extended});

  void sendPointer({required int x, required int y, required int buttons});

  void sendUnicodeText({required String text});

  void sendWheel({
    required int x,
    required int y,
    required int deltaX,
    required int deltaY,
  });

  void setVisible({required bool visible});

  static RemoteDesktopSessionHandle startRdp({
    required RdpSessionParams params,
  }) => RustLib.instance.api
      .crateApiRemoteDesktopRemoteDesktopSessionHandleStartRdp(params: params);

  static RemoteDesktopSessionHandle startVnc({
    required VncSessionParams params,
  }) => RustLib.instance.api
      .crateApiRemoteDesktopRemoteDesktopSessionHandleStartVnc(params: params);
}

class RdpSessionParams {
  /// Loopback address of the SSH local tunnel.
  final String connectHost;
  final int connectPort;

  /// Hostname as seen by the SSH server and used for certificate checks.
  final String serverName;
  final int serverPort;
  final String username;
  final String password;
  final String? domain;
  final String? trustedCertSha256;
  final int width;
  final int height;
  final int scaleFactor;

  const RdpSessionParams({
    required this.connectHost,
    required this.connectPort,
    required this.serverName,
    required this.serverPort,
    required this.username,
    required this.password,
    this.domain,
    this.trustedCertSha256,
    required this.width,
    required this.height,
    required this.scaleFactor,
  });

  @override
  int get hashCode =>
      connectHost.hashCode ^
      connectPort.hashCode ^
      serverName.hashCode ^
      serverPort.hashCode ^
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      trustedCertSha256.hashCode ^
      width.hashCode ^
      height.hashCode ^
      scaleFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSessionParams &&
          runtimeType == other.runtimeType &&
          connectHost == other.connectHost &&
          connectPort == other.connectPort &&
          serverName == other.serverName &&
          serverPort == other.serverPort &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          trustedCertSha256 == other.trustedCertSha256 &&
          width == other.width &&
          height == other.height &&
          scaleFactor == other.scaleFactor;
}

enum RemoteDesktopConnectionState {
  connecting,
  connected,
  reconnecting,
  disconnected,
}

enum RemoteDesktopEndReason {
  closedByUser,
  authenticationFailed,
  certificateRejected,
  configurationError,
  transportError,
  serverDisconnected,
}

@freezed
sealed class RemoteDesktopEvent with _$RemoteDesktopEvent {
  const RemoteDesktopEvent._();

  const factory RemoteDesktopEvent.connectionState({
    required RemoteDesktopConnectionState state,
    required int attempt,
  }) = RemoteDesktopEvent_ConnectionState;
  const factory RemoteDesktopEvent.frame({
    required Uint8List bgra,
    required int width,
    required int height,
    required BigInt sequence,
  }) = RemoteDesktopEvent_Frame;
  const factory RemoteDesktopEvent.resolution({
    required int width,
    required int height,
  }) = RemoteDesktopEvent_Resolution;
  const factory RemoteDesktopEvent.cursorDefault() =
      RemoteDesktopEvent_CursorDefault;
  const factory RemoteDesktopEvent.cursorHidden() =
      RemoteDesktopEvent_CursorHidden;
  const factory RemoteDesktopEvent.cursorPosition({
    required int x,
    required int y,
  }) = RemoteDesktopEvent_CursorPosition;
  const factory RemoteDesktopEvent.cursorBitmap({
    required Uint8List rgba,
    required int width,
    required int height,
    required int hotspotX,
    required int hotspotY,
  }) = RemoteDesktopEvent_CursorBitmap;
  const factory RemoteDesktopEvent.clipboardText({required String text}) =
      RemoteDesktopEvent_ClipboardText;
  const factory RemoteDesktopEvent.certificateRequest({
    required String sha256,
    required String subject,
    required String issuer,
    required String validFrom,
    required String validTo,
    String? previousSha256,
  }) = RemoteDesktopEvent_CertificateRequest;
  const factory RemoteDesktopEvent.error({
    required String message,
    required bool retryable,
  }) = RemoteDesktopEvent_Error;
  const factory RemoteDesktopEvent.ended({
    required RemoteDesktopEndReason reason,
    String? message,
  }) = RemoteDesktopEvent_Ended;
}

class VncSessionParams {
  /// Loopback address of the SSH local tunnel.
  final String connectHost;
  final int connectPort;
  final String? password;
  final bool shared;

  const VncSessionParams({
    required this.connectHost,
    required this.connectPort,
    this.password,
    required this.shared,
  });

  @override
  int get hashCode =>
      connectHost.hashCode ^
      connectPort.hashCode ^
      password.hashCode ^
      shared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VncSessionParams &&
          runtimeType == other.runtimeType &&
          connectHost == other.connectHost &&
          connectPort == other.connectPort &&
          password == other.password &&
          shared == other.shared;
}
