// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Build the full script for a system ("linux" | "bsd" | "windows").
/// `disabled` uses the app's stored displayName format ("Linux.net", ...).
String buildScript({
  required String system,
  required List<CustomCmd> customCmds,
  required List<String> disabled,
  required String buildNumber,
}) => RustLib.instance.api.crateApiScriptBuildScript(
  system: system,
  customCmds: customCmds,
  disabled: disabled,
  buildNumber: buildNumber,
);

/// Command that installs the script on the target (content piped via stdin)
String installCommand({
  required String system,
  required String scriptDir,
  required String scriptPath,
}) => RustLib.instance.api.crateApiScriptInstallCommand(
  system: system,
  scriptDir: scriptDir,
  scriptPath: scriptPath,
);

/// Command that runs one shell function of an installed script
String execCommand({
  required String system,
  required String scriptPath,
  required ShellFuncKind func,
}) => RustLib.instance.api.crateApiScriptExecCommand(
  system: system,
  scriptPath: scriptPath,
  func: func,
);

/// Command-line flag of a shell function ("s", "e", "p", "sd", "r", "sp");
/// wire format owned by sbm_parser::script
String shellFuncFlag({required ShellFuncKind func}) =>
    RustLib.instance.api.crateApiScriptShellFuncFlag(func: func);

/// Split script output into a command key → output map.
/// Async: status output can be large; runs on the Rust thread pool
Future<Map<String, String>> parseScriptOutput({required String raw}) =>
    RustLib.instance.api.crateApiScriptParseScriptOutput(raw: raw);

/// Custom status command; a Vec preserves the Dart map's insertion order,
/// which affects script bytes
class CustomCmd {
  final String name;
  final String cmd;

  const CustomCmd({required this.name, required this.cmd});

  @override
  int get hashCode => name.hashCode ^ cmd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomCmd &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cmd == other.cmd;
}

/// Shell functions of the generated script (mirrors sbm_parser::script::ShellFunc)
enum ShellFuncKind { status, statusExt, process, shutdown, reboot, suspend }
