// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `manager`, `unit`

/// POSIX `sh`, for `ServerExec.run(script, entry: 'sh')`.
String serviceDetectScript() =>
    RustLib.instance.api.crateApiServiceServiceDetectScript();

ServiceProbe serviceParseProbe({required String raw}) =>
    RustLib.instance.api.crateApiServiceServiceParseProbe(raw: raw);

/// The commands one listing of `manager` is read from. They are independent
/// of each other: run them at once.
List<ServiceCommand> serviceListingCommands({required String managerName}) =>
    RustLib.instance.api.crateApiServiceServiceListingCommands(
      managerName: managerName,
    );

/// The listing those commands' outputs make → `ServiceListing` JSON. `Err`
/// is a listing that could not be read at all, in the machine's words.
Future<String> serviceParseListingJson({
  required String managerName,
  required List<ServiceCommandOutput> outputs,
}) => RustLib.instance.api.crateApiServiceServiceParseListingJson(
  managerName: managerName,
  outputs: outputs,
);

/// The command for `action` (`start`, `stop`, `restart`, `enable`,
/// `disable`) on the unit, without `sudo`: whether it needs root is
/// [`service_needs_root`].
String serviceCommand({
  required String managerName,
  required String unitJson,
  required String action,
}) => RustLib.instance.api.crateApiServiceServiceCommand(
  managerName: managerName,
  unitJson: unitJson,
  action: action,
);

/// A systemd user unit is the one that must not: `sudo systemctl --user`
/// talks to root's user manager, not this account's.
bool serviceNeedsRoot({
  required String managerName,
  required String unitJson,
}) => RustLib.instance.api.crateApiServiceServiceNeedsRoot(
  managerName: managerName,
  unitJson: unitJson,
);

/// The unit's last `lines` of log; `None` where the manager keeps none by
/// unit. Read by [`service_parse_recent_log_json`].
String? serviceRecentLogCommand({
  required String managerName,
  required String unitJson,
  required int lines,
}) => RustLib.instance.api.crateApiServiceServiceRecentLogCommand(
  managerName: managerName,
  unitJson: unitJson,
  lines: lines,
);

/// What [`service_recent_log_command`] printed → `ServiceLog` JSON, or
/// `None` where the machine has no log to ask for by unit.
String? serviceParseRecentLogJson({
  required String managerName,
  required String stdout,
  required String stderr,
  required bool succeeded,
}) => RustLib.instance.api.crateApiServiceServiceParseRecentLogJson(
  managerName: managerName,
  stdout: stdout,
  stderr: stderr,
  succeeded: succeeded,
);

/// The whole log, for a terminal; `None` with no such log.
String? serviceLogCommand({
  required String managerName,
  required String unitJson,
}) => RustLib.instance.api.crateApiServiceServiceLogCommand(
  managerName: managerName,
  unitJson: unitJson,
);

/// What prints the unit's definition, for a terminal.
String serviceDefinitionCommand({
  required String managerName,
  required String unitJson,
}) => RustLib.instance.api.crateApiServiceServiceDefinitionCommand(
  managerName: managerName,
  unitJson: unitJson,
);

/// What the manager itself says about the unit, for a terminal.
String serviceUnitStatusCommand({
  required String managerName,
  required String unitJson,
}) => RustLib.instance.api.crateApiServiceServiceUnitStatusCommand(
  managerName: managerName,
  unitJson: unitJson,
);

/// `command` as typed into a terminal: `sudo` in front where it needs root
/// and the account is not root, so the terminal asks for the password.
String serviceTerminalCommand({
  required String command,
  required bool needsRoot,
  required bool isRoot,
}) => RustLib.instance.api.crateApiServiceServiceTerminalCommand(
  command: command,
  needsRoot: needsRoot,
  isRoot: isRoot,
);

/// What may be done to a unit in `state` (`running`, `stopped`, ...) with
/// startup registration `enabled`: the rule every listing's `actions` is.
List<String> serviceActions({required String state, bool? enabled}) => RustLib
    .instance
    .api
    .crateApiServiceServiceActions(state: state, enabled: enabled);

/// One command a listing is read from, by the name its output goes back
/// under ([`service_parse_listing_json`]). `None`: none for this manager.
class ServiceCommand {
  final String name;
  final String? command;

  const ServiceCommand({required this.name, this.command});

  @override
  int get hashCode => name.hashCode ^ command.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceCommand &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          command == other.command;
}

/// What one of those commands printed. A command that could not be run at
/// all is `succeeded: false` with why in `stderr`.
class ServiceCommandOutput {
  final String name;
  final String stdout;
  final String stderr;
  final bool succeeded;

  const ServiceCommandOutput({
    required this.name,
    required this.stdout,
    required this.stderr,
    required this.succeeded,
  });

  @override
  int get hashCode =>
      name.hashCode ^ stdout.hashCode ^ stderr.hashCode ^ succeeded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceCommandOutput &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          succeeded == other.succeeded;
}

/// Which manager the machine runs, from [`service_detect_script`]'s output.
class ServiceProbe {
  /// `systemd`, `procd` or `openrc`; `None` for one this build cannot list.
  final String? manager;

  /// What the machine called it, with its OS: `systemd (Debian GNU/Linux)`.
  final String description;

  const ServiceProbe({this.manager, required this.description});

  @override
  int get hashCode => manager.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceProbe &&
          runtimeType == other.runtimeType &&
          manager == other.manager &&
          description == other.description;
}
