// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `join_rs`, `split_rs`, `to_array32`

/// A fresh x25519 keypair.
///
/// The scalar comes from the operating system, not from a seed this is given:
/// a key exchange private key that a caller could choose is a key exchange an
/// attacker could replay.
X25519KeyPair x25519Keypair() =>
    RustLib.instance.api.crateApiSshAsymX25519Keypair();

/// The shared secret for `private_key` against the peer's `peer_public_key`.
///
/// An all-zero result means the peer sent a low-order point, which is a peer
/// trying to force a known secret rather than a peer with a bad key. Refused
/// here so that no caller has to remember to check.
Uint8List x25519SharedSecret({
  required List<int> privateKey,
  required List<int> peerPublicKey,
}) => RustLib.instance.api.crateApiSshAsymX25519SharedSecret(
  privateKey: privateKey,
  peerPublicKey: peerPublicKey,
);

/// Signs `message` with an SSH Ed25519 private key.
///
/// `private_key` is the 64-byte blob OpenSSH stores: a 32-byte seed followed by
/// the public key it expands to. Only the seed is a secret and only the seed is
/// used; the rest is re-derived, which also means a blob whose halves disagree
/// signs correctly rather than silently producing a signature nothing accepts.
Uint8List ed25519Sign({
  required List<int> privateKey,
  required List<int> message,
}) => RustLib.instance.api.crateApiSshAsymEd25519Sign(
  privateKey: privateKey,
  message: message,
);

/// Whether `signature` is [`message`] signed by `public_key`.
///
/// `false` for a malformed key or signature as much as for a wrong one: a
/// caller asking whether to trust a host has one question, and answering
/// "the signature was the wrong length" through a different channel is how a
/// malformed signature ends up treated as a passing one.
bool ed25519Verify({
  required List<int> publicKey,
  required List<int> message,
  required List<int> signature,
}) => RustLib.instance.api.crateApiSshAsymEd25519Verify(
  publicKey: publicKey,
  message: message,
  signature: signature,
);

/// Signs `message` with an SSH ECDSA private key on `curve`.
///
/// `curve` is the SSH name — `nistp256`, `nistp384`, `nistp521` — and picks the
/// hash with it, as RFC 5656 ties the two together. `private_key` is the
/// scalar, big-endian, at the curve's field width.
///
/// The signature is deterministic (RFC 6979) where dartssh2's is randomized.
/// Both are ECDSA and either verifies against the same public key, but it does
/// mean the two implementations produce different bytes for one input — a test
/// comparing them has to cross-verify rather than compare.
EcdsaSignature ecdsaSign({
  required String curve,
  required List<int> privateKey,
  required List<int> message,
}) => RustLib.instance.api.crateApiSshAsymEcdsaSign(
  curve: curve,
  privateKey: privateKey,
  message: message,
);

/// Whether `r`/`s` is `message` signed by `public_key` on `curve`.
///
/// `public_key` is the uncompressed SEC1 point SSH puts on the wire, `0x04`
/// prefix included. `false` for anything malformed, for the reason
/// [`ed25519_verify`] gives.
bool ecdsaVerify({
  required String curve,
  required List<int> publicKey,
  required List<int> message,
  required List<int> r,
  required List<int> s,
}) => RustLib.instance.api.crateApiSshAsymEcdsaVerify(
  curve: curve,
  publicKey: publicKey,
  message: message,
  r: r,
  s: s,
);

/// The `bcrypt_pbkdf` OpenSSH keys an encrypted private key with.
///
/// Deliberately slow, and staying so: `rounds` comes out of the key file and is
/// not this function's to choose. What changes is only how fast *this* app
/// walks the same rounds — an attacker was never running the Dart one.
Uint8List bcryptPbkdf({
  required List<int> passphrase,
  required List<int> salt,
  required int rounds,
  required int outputLen,
}) => RustLib.instance.api.crateApiSshAsymBcryptPbkdf(
  passphrase: passphrase,
  salt: salt,
  rounds: rounds,
  outputLen: outputLen,
);

/// An ECDSA signature as SSH carries it — two fixed-width big-endian integers.
///
/// Fixed width, not minimal: `r` and `s` are the curve's field size, which is
/// what the crates produce and what the Dart side re-encodes as mpints. A
/// minimal encoding here would make that re-encoding guess where the number
/// started.
class EcdsaSignature {
  final Uint8List r;
  final Uint8List s;

  const EcdsaSignature({required this.r, required this.s});

  @override
  int get hashCode => r.hashCode ^ s.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EcdsaSignature &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          s == other.s;
}

/// One end of a key exchange: the scalar to keep and the point to send.
class X25519KeyPair {
  final Uint8List privateKey;
  final Uint8List publicKey;

  const X25519KeyPair({required this.privateKey, required this.publicKey});

  @override
  int get hashCode => privateKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is X25519KeyPair &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey;
}
