// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CipherState`, `MacState`, `Mode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshBlockCipher>>
abstract class SshBlockCipher implements RustOpaqueInterface {
  /// The unit [`process`](Self::process) works in, which is also the packet
  /// alignment the caller pads to.
  int blockSize();

  /// A cipher for [`algorithm`], an SSH algorithm name as it appears on the
  /// wire — `aes256-ctr`, `aes128-cbc` and so on.
  ///
  /// `Err` for a name this does not implement, which is the caller's signal
  /// to use its own implementation rather than a failure. Also `Err` for a
  /// key or IV of the wrong length, which is a caller bug: SSH derives both
  /// from the exchange hash at the length the algorithm names.
  ///
  /// `for_encryption` picks the direction. It is meaningless for CTR — the
  /// keystream is the same either way — and is what selects between the two
  /// distinct CBC implementations.
  factory SshBlockCipher({
    required String algorithm,
    required List<int> key,
    required List<int> iv,
    required bool forEncryption,
  }) => RustLib.instance.api.crateApiSshCryptoSshBlockCipherNew(
    algorithm: algorithm,
    key: key,
    iv: iv,
    forEncryption: forEncryption,
  );

  /// Transforms [`data`] and advances the cipher past it.
  ///
  /// Call order is the packet order on the wire and cannot be replayed or
  /// skipped — a CTR counter and a CBC chaining block are both positions in
  /// one stream.
  ///
  /// CBC requires whole blocks and says so rather than padding: an SSH packet
  /// is aligned to the block size before it is encrypted, so a length that is
  /// not a multiple of one is a framing bug and silently absorbing it would
  /// hide the bug and corrupt the stream. CTR is a stream cipher and takes
  /// any length.
  Uint8List process({required List<int> data});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshMac>>
abstract class SshMac implements RustOpaqueInterface {
  /// The tag over [`data`], which is one whole packet's MAC input.
  ///
  /// Takes the input in one piece rather than incrementally: a caller that
  /// feeds a sequence number and then a packet would otherwise pay a crossing
  /// per piece, and joining them costs one copy of bytes it is already
  /// holding. The keyed state is cloned per call, so this leaves nothing
  /// behind and cannot be desynchronised by a packet that is dropped.
  Uint8List compute({required List<int> data});

  /// The tag length in bytes, after any truncation.
  int macSize();

  /// A MAC for [`algorithm`], an SSH algorithm name with any `-etm@...` or
  /// `-96` suffix already stripped: neither changes how the tag is computed.
  /// Encrypt-then-MAC changes only *what* the caller feeds in, and the `-96`
  /// variants are a plain truncation, which is what [`mac_size`] expresses.
  ///
  /// `Err` for a name this does not implement, which is the caller's signal
  /// to use its own implementation rather than a failure.
  factory SshMac({
    required String algorithm,
    required List<int> key,
    required int macSize,
  }) => RustLib.instance.api.crateApiSshCryptoSshMacNew(
    algorithm: algorithm,
    key: key,
    macSize: macSize,
  );
}
