// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `json_err`, `spec_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`

/// Host probe: Proxmox VE, a container, or `virsh` answering this user
String virtProbeScript() => RustLib.instance.api.crateApiVirtVirtProbeScript();

/// Guest list, state, and raw counters in one round trip
String virtOverviewScript() =>
    RustLib.instance.api.crateApiVirtVirtOverviewScript();

/// Display URI and XML for one domain (`domain`: UUID preferred, or name)
String virtDomainDetailScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtDomainDetailScript(domain: domain);

/// One power action on one domain
String virtActionScript({
  required VirtActionKind action,
  required String domain,
}) => RustLib.instance.api.crateApiVirtVirtActionScript(
  action: action,
  domain: domain,
);

/// Command line for an interactive serial console in a terminal session
String virtConsoleCommand({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtConsoleCommand(domain: domain);

/// [`virt_probe_script`]'s output → `VirtHostProbe` JSON
Future<String> parseVirtProbeJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtProbeJson(raw: raw);

/// [`virt_overview_script`]'s output → `VirtOverview` JSON
Future<String> parseVirtOverviewJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtOverviewJson(raw: raw);

/// Display and VNC password, for opening a graphical console
String virtVncConsoleScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtVncConsoleScript(domain: domain);

/// [`virt_vnc_console_script`]'s output → `VirtVncConsoleInfo` JSON. Holds
/// the password: never logged.
Future<String> parseVirtVncConsoleJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtVncConsoleJson(raw: raw);

/// [`virt_domain_detail_script`]'s output → `VirtDomainDetail` JSON
Future<String> parseVirtDomainDetailJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtDomainDetailJson(raw: raw);

/// [`virt_action_script`]'s output: `Ok` when virsh accepted the action
void parseVirtAction({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtAction(raw: raw);

/// Every snapshot of one domain
String virtSnapshotsScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtSnapshotsScript(domain: domain);

/// [`virt_snapshots_script`]'s output → `Vec<VirtSnapshotInfo>` JSON
Future<String> parseVirtSnapshotsJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapshotsJson(raw: raw);

/// An internal snapshot; with memory when the domain is active. Parse with
/// [`parse_virt_action`].
String virtSnapshotCreateScript({
  required String domain,
  required String name,
  String? description,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotCreateScript(
  domain: domain,
  name: name,
  description: description,
);

/// Revert to a snapshot; `running` starts the domain afterwards. Parse with
/// [`parse_virt_action`].
String virtSnapshotRevertScript({
  required String domain,
  required String name,
  required bool running,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotRevertScript(
  domain: domain,
  name: name,
  running: running,
);

/// Delete one snapshot, then the files libvirt leaves behind
/// ([`parse_virt_snap_delete_leftovers`]) through their `pools`. Parse with
/// [`parse_virt_snapshot_delete`].
String virtSnapshotDeleteScript({
  required String domain,
  required String name,
  required List<String> pools,
  required List<String> leftovers,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotDeleteScript(
  domain: domain,
  name: name,
  pools: pools,
  leftovers: leftovers,
);

/// [`virt_snapshot_delete_script`]'s output: `Ok` once the snapshot is gone;
/// a file it left that could not be deleted is an error naming it
Future<void> parseVirtSnapshotDelete({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapshotDelete(raw: raw);

/// The disk chain of a domain (external snapshots): the definition, where
/// each device is now, and each one's chain as QEMU resolves it
String virtSnapChainScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtSnapChainScript(domain: domain);

/// [`virt_snap_chain_script`]'s output → `VirtSnapChain` JSON
Future<String> parseVirtSnapChainJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapChainJson(raw: raw);

/// What deciding whether the host would refuse deleting or reverting to
/// snapshot `name` needs: its layers, the chain, the security model and the
/// AppArmor profile's `deny` lines. Parse with
/// [`parse_virt_snap_delete_refusal`] or [`parse_virt_snap_revert_refusal`].
String virtSnapCheckScript({required String domain, required String name}) =>
    RustLib.instance.api.crateApiVirtVirtSnapCheckScript(
      domain: domain,
      name: name,
    );

/// [`virt_snap_check_script`]'s output → why the host would refuse the
/// delete (AppArmor denying the commit), or `None`
Future<String?> parseVirtSnapDeleteRefusal({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapDeleteRefusal(raw: raw);

/// [`virt_snap_check_script`]'s output → the files deleting the snapshot
/// leaves behind (its overlays off the current chain), for
/// [`virt_snapshot_delete_script`] to delete
Future<List<String>> parseVirtSnapDeleteLeftovers({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapDeleteLeftovers(raw: raw);

/// [`virt_snap_check_script`]'s output → why a revert would leave the guest
/// unable to start (AppArmor's helper refused the new overlay), or `None`
Future<String?> parseVirtSnapRevertRefusal({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapRevertRefusal(raw: raw);

/// An external snapshot (disks only, `--atomic`), `overlays` being
/// `(target, path)` per disk. Parse with [`parse_virt_action`].
String virtSnapshotExternalScript({
  required String domain,
  required String name,
  String? description,
  required List<(String, String)> overlays,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotExternalScript(
  domain: domain,
  name: name,
  description: description,
  overlays: overlays,
);

/// A snapshot's configuration and the guest's current one. Parse with
/// [`parse_virt_snap_diff_json`].
String virtSnapDiffScript({required String domain, required String name}) =>
    RustLib.instance.api.crateApiVirtVirtSnapDiffScript(
      domain: domain,
      name: name,
    );

/// [`virt_snap_diff_script`]'s output → `Vec<VirtSnapDiff>` JSON
Future<String> parseVirtSnapDiffJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapDiffJson(raw: raw);

/// Why an external snapshot cannot be taken, from a `VirtSnapChain` JSON
String? virtExternalSnapshotRefusal({required String chainJson}) => RustLib
    .instance
    .api
    .crateApiVirtVirtExternalSnapshotRefusal(chainJson: chainJson);

/// Why no snapshot at all can be taken, from a `VirtSnapChain` JSON
String? virtSnapshotRefusal({required String chainJson}) =>
    RustLib.instance.api.crateApiVirtVirtSnapshotRefusal(chainJson: chainJson);

/// Pools, volume names and every domain's disks
String virtStorageScript() =>
    RustLib.instance.api.crateApiVirtVirtStorageScript();

/// [`virt_storage_script`]'s output → `VirtStorage` JSON
Future<String> parseVirtStorageJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtStorageJson(raw: raw);

/// What each of `names` in `pool` is: format and sizes
String virtVolumesScript({required String pool, required List<String> names}) =>
    RustLib.instance.api.crateApiVirtVirtVolumesScript(
      pool: pool,
      names: names,
    );

/// [`virt_volumes_script`]'s output → `Vec<VirtVolume>` JSON
Future<String> parseVirtVolumesJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtVolumesJson(raw: raw);

/// Networks, DHCP leases and every domain's interfaces
String virtNetworksScript() =>
    RustLib.instance.api.crateApiVirtVirtNetworksScript();

/// [`virt_networks_script`]'s output → `VirtNetworks` JSON
Future<String> parseVirtNetworksJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtNetworksJson(raw: raw);

/// Editing an existing network (phase 10): `op_json` is a
/// `sbm_parser::virt_net::VirtNetOp`. Parse with [`parse_virt_net_change`].
String virtNetChangeScript({required String opJson}) =>
    RustLib.instance.api.crateApiVirtVirtNetChangeScript(opJson: opJson);

/// [`virt_net_change_script`]'s output: `Ok` once the definition (and, when
/// asked for, the running network) has the change
Future<void> parseVirtNetChange({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtNetChange(raw: raw);

/// What the host can run a new domain as (`domcapabilities`)
String virtCreateHostScript() =>
    RustLib.instance.api.crateApiVirtVirtCreateHostScript();

/// [`virt_create_host_script`]'s output → `VirtCreateHost` JSON
Future<String> parseVirtCreateHostJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateHostJson(raw: raw);

/// A new domain's disk (empty, or a copy of a cloud image) and its
/// cloud-init seed; `spec_json` is a `VirtCreateSpec`
String virtCreateVolumeScript({required String specJson}) =>
    RustLib.instance.api.crateApiVirtVirtCreateVolumeScript(specJson: specJson);

/// [`virt_create_volume_script`]'s output → `VirtCreateVolumes` JSON (the
/// disk's and the seed's paths)
Future<String> parseVirtCreateVolumesJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateVolumesJson(raw: raw);

/// `$6$<salt>$…`: a cloud-init password as SHA-512 crypt, so only the hash
/// ever leaves the app. `salt` is up to 16 of `./0-9A-Za-z`, drawn from a
/// secure source by the caller. Synchronous: the password is at most
/// `PASSWORD_MAX` (1 KiB) bytes, which bounds the hashing to milliseconds;
/// a longer one is refused.
String virtHashPassword({required String password, required String salt}) =>
    RustLib.instance.api.crateApiVirtVirtHashPassword(
      password: password,
      salt: salt,
    );

/// A clone's disks (`VirtCloneSpec` JSON), each copied or made empty in
/// its source's pool
String virtCloneVolumesScript({required String specJson}) =>
    RustLib.instance.api.crateApiVirtVirtCloneVolumesScript(specJson: specJson);

/// [`virt_clone_volumes_script`]'s output: the new volumes' paths, in order
Future<List<String>> parseVirtCloneVolumes({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCloneVolumes(raw: raw);

/// Defines the clone of `base_xml` called `name` on `disks_json`
/// (`[[target, path], ...]`); parse with [`parse_virt_create_json`]
String virtCloneDefineScript({
  required String baseXml,
  required String name,
  required String disksJson,
}) => RustLib.instance.api.crateApiVirtVirtCloneDefineScript(
  baseXml: baseXml,
  name: name,
  disksJson: disksJson,
);

/// Defines (and optionally starts) the domain on that disk
String virtDefineScript({required String specJson}) =>
    RustLib.instance.api.crateApiVirtVirtDefineScript(specJson: specJson);

/// [`virt_define_script`]'s output → `VirtCreated` JSON
Future<String> parseVirtCreateJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateJson(raw: raw);

/// `undefine`, with the volumes of the disk targets in `storage` (none keeps
/// them all), and the domain's own cloud-init `seed` and the `chain` files
/// its external snapshots left (after refreshing `pools`) after it. Parse
/// with [`parse_virt_undefine`].
String virtUndefineScript({
  required String domain,
  required List<String> storage,
  String? seed,
  required List<String> pools,
  required List<String> chain,
}) => RustLib.instance.api.crateApiVirtVirtUndefineScript(
  domain: domain,
  storage: storage,
  seed: seed,
  pools: pools,
  chain: chain,
);

/// [`virt_undefine_script`]'s output: `Ok` once the domain (and its seed)
/// are gone
void parseVirtUndefine({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtUndefine(raw: raw);

/// A domain's cloud-init seed at `seed` (its path, as the domain's metadata
/// names it), read back from its volume. Parse with
/// [`parse_virt_seed_read_json`].
String virtSeedReadScript({required String seed}) =>
    RustLib.instance.api.crateApiVirtVirtSeedReadScript(seed: seed);

/// [`virt_seed_read_script`]'s output → `VirtSeedRead` JSON: what the seed
/// says (its password as the hash in it), whether it holds more than the
/// app writes, and its revision
Future<String> parseVirtSeedReadJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSeedReadJson(raw: raw);

/// The seed at `seed` rewritten in place from `cloud_init_json` (a
/// `VirtCloudInit`), made from the read of `revision`; `tools` narrows the
/// ISO tools tried (none: all, in their order). Parse with
/// [`parse_virt_seed_update`].
String virtSeedUpdateScript({
  required String seed,
  required String revision,
  required String cloudInitJson,
  List<String>? tools,
}) => RustLib.instance.api.crateApiVirtVirtSeedUpdateScript(
  seed: seed,
  revision: revision,
  cloudInitJson: cloudInitJson,
  tools: tools,
);

/// [`virt_seed_update_script`]'s output: `Ok` once the new seed is in
/// place; `Conflict` when the seed changed since it was read
void parseVirtSeedUpdate({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSeedUpdate(raw: raw);

/// A domain's hardware, persistent and running, in one round trip
String virtHardwareScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtHardwareScript(domain: domain);

/// [`virt_hardware_script`]'s output → `VirtHardwareInfo` JSON
Future<String> parseVirtHardwareJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtHardwareJson(raw: raw);

/// One hardware change; `change_json` is a `VirtHwChange`, `base_xml` the
/// persistent definition it was made from. Parse with
/// [`parse_virt_hardware_change_json`].
String virtHardwareChangeScript({
  required String domain,
  required bool running,
  String? baseXml,
  required String changeJson,
}) => RustLib.instance.api.crateApiVirtVirtHardwareChangeScript(
  domain: domain,
  running: running,
  baseXml: baseXml,
  changeJson: changeJson,
);

/// [`virt_hardware_change_script`]'s output → `VirtHwOutcome` JSON
Future<String> parseVirtHardwareChangeJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtHardwareChangeJson(raw: raw);

/// Which pool types the daemon has a backend for (`pool-capabilities`).
/// Parse with [`parse_virt_pool_types`].
String virtPoolTypesScript() =>
    RustLib.instance.api.crateApiVirtVirtPoolTypesScript();

/// [`virt_pool_types_script`]'s output → the pool types this app makes that
/// the host supports, in the order offered; `None` where it could not say
List<String>? parseVirtPoolTypes({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtPoolTypes(raw: raw);

/// The host's firmware descriptors (`/usr/share/qemu/firmware/*.json`), for
/// what a new domain can boot with. Parse with
/// [`parse_virt_firmware_json`].
String virtFirmwareScript() =>
    RustLib.instance.api.crateApiVirtVirtFirmwareScript();

/// [`virt_firmware_script`]'s output → `Vec<FirmwareDescriptor>` JSON
Future<String> parseVirtFirmwareJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtFirmwareJson(raw: raw);

/// The host's USB and PCI devices, for passing one to a guest
String virtHostDevicesScript() =>
    RustLib.instance.api.crateApiVirtVirtHostDevicesScript();

/// [`virt_host_devices_script`]'s output → `VirtHostDevices` JSON
Future<String> parseVirtHostDevicesJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtHostDevicesJson(raw: raw);

/// One change to the host's storage or networks; `op_json` is a
/// `VirtResourceOp`. Parse with [`parse_virt_resource`].
String virtResourceScript({required String opJson}) =>
    RustLib.instance.api.crateApiVirtVirtResourceScript(opJson: opJson);

/// [`virt_resource_script`]'s output: `Ok` when every step ran
void parseVirtResource({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtResource(raw: raw);

/// The command writing its stdin into a volume, for a channel that carries
/// bytes; see `sbm_parser::virt_manage::vol_upload_command` for what goes
/// on stdin, in which order
String virtVolUploadCommand({
  required String pool,
  required String name,
  required VirtUploadEntryKind entry,
}) => RustLib.instance.api.crateApiVirtVirtVolUploadCommand(
  pool: pool,
  name: name,
  entry: entry,
);

/// [`virt_vol_upload_command`]'s output: `true` uploaded, `false` stopped
/// before virsh because the first line was not the go line
bool parseVirtVolUpload({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtVolUpload(raw: raw);

/// The line sent before an upload's bytes
String virtUploadGoLine() =>
    RustLib.instance.api.crateApiVirtVirtUploadGoLine();

/// What the upload command prints once the bytes may follow
String virtUploadReadyMarker() =>
    RustLib.instance.api.crateApiVirtVirtUploadReadyMarker();

/// Power actions (mirrors sbm_parser::virt::VirtAction)
enum VirtActionKind {
  start,

  /// ACPI shutdown request
  shutdown,

  /// ACPI reboot request
  reboot,

  /// `virsh destroy`
  forceStop,

  /// Pause vCPUs
  suspend,
  resume,
}

/// Classes of [`VirtFfiError`] (mirrors sbm_parser::virt::VirtError)
enum VirtErrorKind {
  /// `virsh` is not on PATH
  notInstalled,

  /// The daemon refused this user; retrying as root is the fix
  permissionDenied,

  /// The daemon could not be reached
  connectFailed,
  domainNotFound,

  /// The domain's state does not allow the operation
  invalidState,

  /// A domain or volume of that name is there already
  exists,

  /// The definition changed since it was read
  conflict,

  /// Any other virsh failure
  command,

  /// Output cut off or not what the script prints
  malformed,
}

/// A classified virsh failure; `message` is virsh's own error text.
class VirtFfiError implements FrbException {
  final VirtErrorKind kind;
  final String message;

  const VirtFfiError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtFfiError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// How the upload command reaches the daemon (mirrors
/// sbm_parser::virt_manage::VirtUploadEntry)
enum VirtUploadEntryKind {
  /// As this account
  direct,

  /// `sudo -n`
  sudoNoPassword,

  /// `sudo -S`, the password first on stdin
  sudoPassword,
}
