// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:server_box/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `json_err`, `spec_of`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Host probe: Proxmox VE, a container, or `virsh` answering this user
String virtProbeScript() => RustLib.instance.api.crateApiVirtVirtProbeScript();

/// Guest list, state, and raw counters in one round trip
String virtOverviewScript() =>
    RustLib.instance.api.crateApiVirtVirtOverviewScript();

/// Display URI and XML for one domain (`domain`: UUID preferred, or name)
String virtDomainDetailScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtDomainDetailScript(domain: domain);

/// One power action on one domain
String virtActionScript({
  required VirtActionKind action,
  required String domain,
}) => RustLib.instance.api.crateApiVirtVirtActionScript(
  action: action,
  domain: domain,
);

/// Command line for an interactive serial console in a terminal session
String virtConsoleCommand({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtConsoleCommand(domain: domain);

/// [`virt_probe_script`]'s output → `VirtHostProbe` JSON
Future<String> parseVirtProbeJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtProbeJson(raw: raw);

/// [`virt_overview_script`]'s output → `VirtOverview` JSON
Future<String> parseVirtOverviewJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtOverviewJson(raw: raw);

/// [`virt_domain_detail_script`]'s output → `VirtDomainDetail` JSON
Future<String> parseVirtDomainDetailJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtDomainDetailJson(raw: raw);

/// [`virt_action_script`]'s output: `Ok` when virsh accepted the action
void parseVirtAction({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtAction(raw: raw);

/// Every snapshot of one domain
String virtSnapshotsScript({required String domain}) =>
    RustLib.instance.api.crateApiVirtVirtSnapshotsScript(domain: domain);

/// [`virt_snapshots_script`]'s output → `Vec<VirtSnapshotInfo>` JSON
Future<String> parseVirtSnapshotsJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtSnapshotsJson(raw: raw);

/// An internal snapshot; with memory when the domain is active. Parse with
/// [`parse_virt_action`].
String virtSnapshotCreateScript({
  required String domain,
  required String name,
  String? description,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotCreateScript(
  domain: domain,
  name: name,
  description: description,
);

/// Revert to a snapshot; `running` starts the domain afterwards. Parse with
/// [`parse_virt_action`].
String virtSnapshotRevertScript({
  required String domain,
  required String name,
  required bool running,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotRevertScript(
  domain: domain,
  name: name,
  running: running,
);

/// Delete one snapshot. Parse with [`parse_virt_action`].
String virtSnapshotDeleteScript({
  required String domain,
  required String name,
}) => RustLib.instance.api.crateApiVirtVirtSnapshotDeleteScript(
  domain: domain,
  name: name,
);

/// Pools, volume names and every domain's disks
String virtStorageScript() =>
    RustLib.instance.api.crateApiVirtVirtStorageScript();

/// [`virt_storage_script`]'s output → `VirtStorage` JSON
Future<String> parseVirtStorageJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtStorageJson(raw: raw);

/// What each of `names` in `pool` is: format and sizes
String virtVolumesScript({required String pool, required List<String> names}) =>
    RustLib.instance.api.crateApiVirtVirtVolumesScript(
      pool: pool,
      names: names,
    );

/// [`virt_volumes_script`]'s output → `Vec<VirtVolume>` JSON
Future<String> parseVirtVolumesJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtVolumesJson(raw: raw);

/// Networks, DHCP leases and every domain's interfaces
String virtNetworksScript() =>
    RustLib.instance.api.crateApiVirtVirtNetworksScript();

/// [`virt_networks_script`]'s output → `VirtNetworks` JSON
Future<String> parseVirtNetworksJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtNetworksJson(raw: raw);

/// What the host can run a new domain as (`domcapabilities`)
String virtCreateHostScript() =>
    RustLib.instance.api.crateApiVirtVirtCreateHostScript();

/// [`virt_create_host_script`]'s output → `VirtCreateHost` JSON
Future<String> parseVirtCreateHostJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateHostJson(raw: raw);

/// A new domain's disk and its path; `spec_json` is a `VirtCreateSpec`
String virtCreateVolumeScript({required String specJson}) =>
    RustLib.instance.api.crateApiVirtVirtCreateVolumeScript(specJson: specJson);

/// [`virt_create_volume_script`]'s output: the new volume's path
Future<String> parseVirtCreateVolume({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateVolume(raw: raw);

/// Defines (and optionally starts) the domain on that disk
String virtDefineScript({required String specJson}) =>
    RustLib.instance.api.crateApiVirtVirtDefineScript(specJson: specJson);

/// [`virt_define_script`]'s output → `VirtCreated` JSON
Future<String> parseVirtCreateJson({required String raw}) =>
    RustLib.instance.api.crateApiVirtParseVirtCreateJson(raw: raw);

/// `undefine`, with the volumes of the disk targets in `storage` (none keeps
/// them all). Parse with [`parse_virt_action`].
String virtUndefineScript({
  required String domain,
  required List<String> storage,
}) => RustLib.instance.api.crateApiVirtVirtUndefineScript(
  domain: domain,
  storage: storage,
);

/// Power actions (mirrors sbm_parser::virt::VirtAction)
enum VirtActionKind {
  start,

  /// ACPI shutdown request
  shutdown,

  /// ACPI reboot request
  reboot,

  /// `virsh destroy`
  forceStop,

  /// Pause vCPUs
  suspend,
  resume,
}

/// Classes of [`VirtFfiError`] (mirrors sbm_parser::virt::VirtError)
enum VirtErrorKind {
  /// `virsh` is not on PATH
  notInstalled,

  /// The daemon refused this user; retrying as root is the fix
  permissionDenied,

  /// The daemon could not be reached
  connectFailed,
  domainNotFound,

  /// The domain's state does not allow the operation
  invalidState,

  /// A domain or volume of that name is there already
  exists,

  /// Any other virsh failure
  command,

  /// Output cut off or not what the script prints
  malformed,
}

/// A classified virsh failure; `message` is virsh's own error text.
class VirtFfiError implements FrbException {
  final VirtErrorKind kind;
  final String message;

  const VirtFfiError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtFfiError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}
