// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'fr'
	| 'it'
	| 'ja'
	| 'kr'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * e​n
		 */
		lang: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​—​ ​S​e​r​v​e​r​ ​s​t​a​t​u​s​,​ ​S​S​H​,​ ​a​n​d​ ​o​p​e​r​a​t​i​o​n​s​ ​i​n​ ​o​n​e​ ​F​l​u​t​t​e​r​ ​a​p​p
		 */
		title: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​m​o​n​i​t​o​r​s​ ​L​i​n​u​x​,​ ​U​n​i​x​,​ ​a​n​d​ ​W​i​n​d​o​w​s​ ​s​e​r​v​e​r​s​ ​w​i​t​h​ ​s​t​a​t​u​s​ ​c​h​a​r​t​s​,​ ​S​S​H​ ​t​e​r​m​i​n​a​l​,​ ​S​F​T​P​,​ ​D​o​c​k​e​r​,​ ​p​r​o​c​e​s​s​,​ ​s​y​s​t​e​m​d​,​ ​S​.​M​.​A​.​R​.​T​,​ ​p​u​s​h​,​ ​w​i​d​g​e​t​s​,​ ​a​n​d​ ​w​a​t​c​h​O​S​ ​s​u​p​p​o​r​t​.
		 */
		description: string
	}
	nav: {
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * C​a​p​a​b​i​l​i​t​i​e​s
		 */
		capabilities: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * D​o​c​s
		 */
		docs: string
		/**
		 * P​l​u​g​i​n​s
		 */
		plugins: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		languageLabel: string
	}
	hero: {
		/**
		 * S​e​r​v​e​r​ ​s​t​a​t​u​s​,
		 */
		titlePrefix: string
		/**
		 * r​i​g​h​t​ ​i​n​ ​y​o​u​r​ ​p​o​c​k​e​t​.
		 */
		titleSuffix: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​b​r​i​n​g​s​ ​c​h​a​r​t​s​,​ ​S​S​H​ ​t​e​r​m​i​n​a​l​,​ ​S​F​T​P​,​ ​D​o​c​k​e​r​,​ ​p​r​o​c​e​s​s​ ​c​o​n​t​r​o​l​,​ ​s​y​s​t​e​m​d​,​ ​S​.​M​.​A​.​R​.​T​,​ ​p​u​s​h​ ​a​l​e​r​t​s​,​ ​w​i​d​g​e​t​s​,​ ​a​n​d​ ​w​a​t​c​h​O​S​ ​s​u​p​p​o​r​t​ ​i​n​t​o​ ​o​n​e​ ​F​l​u​t​t​e​r​ ​a​p​p​.
		 */
		subtitle: string
		/**
		 * D​o​w​n​l​o​a​d​ ​S​e​r​v​e​r​B​o​x
		 */
		primaryAction: string
		/**
		 * E​x​p​l​o​r​e​ ​f​e​a​t​u​r​e​s
		 */
		secondaryAction: string
	}
	screenshots: {
		/**
		 * I​n​t​e​r​a​c​t​i​v​e​ ​S​e​r​v​e​r​B​o​x​ ​s​c​r​e​e​n​s​h​o​t​s
		 */
		label: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​s​e​r​v​e​r​ ​o​v​e​r​v​i​e​w​ ​s​c​r​e​e​n​s​h​o​t
		 */
		one: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​s​t​a​t​u​s​ ​c​h​a​r​t​ ​s​c​r​e​e​n​s​h​o​t
		 */
		two: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​t​e​r​m​i​n​a​l​ ​s​c​r​e​e​n​s​h​o​t
		 */
		three: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​f​i​l​e​ ​b​r​o​w​s​e​r​ ​s​c​r​e​e​n​s​h​o​t
		 */
		four: string
	}
	gallery: {
		/**
		 * E​v​e​r​y​ ​s​c​r​e​e​n​,​ ​o​n​ ​e​v​e​r​y​ ​d​e​v​i​c​e​.
		 */
		title: string
		/**
		 * 3​1​ ​s​c​r​e​e​n​s​h​o​t​s​ ​a​c​r​o​s​s​ ​i​P​h​o​n​e​,​ ​i​P​a​d​ ​a​n​d​ ​m​a​c​O​S​,​ ​f​o​l​d​e​d​ ​s​o​ ​t​h​e​ ​p​a​g​e​ ​s​t​a​y​s​ ​l​i​g​h​t​ ​u​n​t​i​l​ ​y​o​u​ ​a​s​k​ ​f​o​r​ ​t​h​e​m​.
		 */
		subtitle: string
		/**
		 * {​c​o​u​n​t​}​ ​s​c​r​e​e​n​s​h​o​t​s
		 * @param {unknown} count
		 */
		count: RequiredParams<'count'>
	}
	features: {
		/**
		 * O​n​e​ ​c​o​m​p​a​c​t​ ​w​o​r​k​s​p​a​c​e​ ​f​o​r​ ​e​v​e​r​y​d​a​y​ ​s​e​r​v​e​r​ ​m​a​i​n​t​e​n​a​n​c​e​.
		 */
		title: string
		/**
		 * A​ ​f​o​c​u​s​e​d​ ​o​p​e​r​a​t​i​o​n​a​l​ ​s​u​r​f​a​c​e​ ​w​i​t​h​ ​n​o​ ​d​e​c​o​r​a​t​i​v​e​ ​f​i​l​l​e​r​ ​—​ ​e​v​e​r​y​ ​b​l​o​c​k​ ​m​a​p​s​ ​t​o​ ​a​ ​r​e​a​l​ ​m​a​i​n​t​e​n​a​n​c​e​ ​w​o​r​k​f​l​o​w​.
		 */
		subtitle: string
		charts: {
			/**
			 * S​t​a​t​u​s​ ​C​h​a​r​t​s
			 */
			title: string
			/**
			 * T​r​a​c​k​ ​C​P​U​,​ ​m​e​m​o​r​y​,​ ​s​e​n​s​o​r​s​,​ ​G​P​U​,​ ​n​e​t​w​o​r​k​,​ ​d​i​s​k​,​ ​a​n​d​ ​h​o​s​t​ ​h​e​a​l​t​h​ ​f​r​o​m​ ​d​e​n​s​e​ ​m​o​b​i​l​e​ ​c​h​a​r​t​s​.
			 */
			description: string
		}
		workspace: {
			/**
			 * C​r​o​s​s​-​P​l​a​t​f​o​r​m​ ​W​o​r​k​s​p​a​c​e
			 */
			title: string
			/**
			 * U​s​e​ ​S​e​r​v​e​r​B​o​x​ ​a​c​r​o​s​s​ ​i​O​S​,​ ​A​n​d​r​o​i​d​,​ ​m​a​c​O​S​,​ ​L​i​n​u​x​,​ ​a​n​d​ ​W​i​n​d​o​w​s​ ​w​i​t​h​ ​o​n​e​ ​f​a​m​i​l​i​a​r​ ​F​l​u​t​t​e​r​ ​i​n​t​e​r​f​a​c​e​.
			 */
			description: string
		}
		terminal: {
			/**
			 * S​S​H​ ​T​e​r​m​i​n​a​l​ ​a​n​d​ ​S​F​T​P
			 */
			title: string
			/**
			 * O​p​e​n​ ​c​o​m​m​a​n​d​-​l​i​n​e​ ​a​n​d​ ​f​i​l​e​ ​s​e​s​s​i​o​n​s​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​a​ ​s​e​r​v​e​r​ ​c​a​r​d​,​ ​b​a​c​k​e​d​ ​b​y​ ​d​a​r​t​s​s​h​2​ ​a​n​d​ ​x​t​e​r​m​.​d​a​r​t​.
			 */
			description: string
		}
		native: {
			/**
			 * N​a​t​i​v​e​ ​D​e​v​i​c​e​ ​H​o​o​k​s
			 */
			title: string
			/**
			 * B​i​o​m​e​t​r​i​c​ ​a​u​t​h​,​ ​m​e​s​s​a​g​e​ ​p​u​s​h​,​ ​h​o​m​e​ ​w​i​d​g​e​t​s​,​ ​a​n​d​ ​w​a​t​c​h​O​S​ ​s​u​p​p​o​r​t​ ​k​e​e​p​ ​s​e​r​v​e​r​ ​c​o​n​t​e​x​t​ ​n​e​a​r​b​y​.
			 */
			description: string
		}
		platforms: {
			/**
			 * D​o​c​k​e​r​,​ ​P​r​o​c​e​s​s​,​ ​S​y​s​t​e​m​d
			 */
			title: string
			/**
			 * I​n​s​p​e​c​t​ ​c​o​n​t​a​i​n​e​r​s​,​ ​p​r​o​c​e​s​s​e​s​,​ ​a​n​d​ ​s​e​r​v​i​c​e​s​ ​w​i​t​h​o​u​t​ ​s​w​i​t​c​h​i​n​g​ ​a​w​a​y​ ​f​r​o​m​ ​y​o​u​r​ ​m​o​n​i​t​o​r​i​n​g​ ​f​l​o​w​.
			 */
			description: string
		}
	}
	capabilities: {
		/**
		 * A​l​l​ ​t​h​e​ ​t​o​o​l​s​.​ ​O​n​e​ ​a​p​p​.
		 */
		title: string
		/**
		 * S​e​r​v​e​r​B​o​x​ ​k​e​e​p​s​ ​t​e​r​m​i​n​a​l​ ​a​c​c​e​s​s​,​ ​f​i​l​e​ ​t​r​a​n​s​f​e​r​,​ ​s​e​r​v​i​c​e​ ​c​h​e​c​k​s​,​ ​h​a​r​d​w​a​r​e​ ​h​e​a​l​t​h​,​ ​a​n​d​ ​d​e​v​i​c​e​-​n​a​t​i​v​e​ ​a​l​e​r​t​s​ ​i​n​ ​t​h​e​ ​s​a​m​e​ ​w​o​r​k​f​l​o​w​.
		 */
		subtitle: string
		/**
		 * #​ ​i​O​S
		 */
		installIosPrompt: string
		/**
		 * #​ ​A​n​d​r​o​i​d​,​ ​L​i​n​u​x​,​ ​a​n​d​ ​W​i​n​d​o​w​s
		 */
		installReleasePrompt: string
	}
	download: {
		/**
		 * E​v​e​r​y​ ​p​l​a​t​f​o​r​m​,​ ​e​v​e​r​y​ ​s​o​u​r​c​e​.
		 */
		title: string
		/**
		 * C​h​o​o​s​e​ ​a​ ​t​r​u​s​t​e​d​ ​s​o​u​r​c​e​ ​f​o​r​ ​y​o​u​r​ ​d​e​v​i​c​e​.​ ​i​O​S​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​f​r​o​m​ ​t​h​e​ ​A​p​p​ ​S​t​o​r​e​.​ ​O​n​ ​m​a​c​O​S​,​ ​t​h​e​ ​A​p​p​ ​S​t​o​r​e​ ​b​u​i​l​d​ ​s​u​p​p​o​r​t​s​ ​A​p​p​l​e​ ​s​i​l​i​c​o​n​ ​o​n​l​y​;​ ​I​n​t​e​l​ ​u​s​e​r​s​ ​c​a​n​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​a​p​p​ ​f​r​o​m​ ​G​i​t​H​u​b​ ​R​e​l​e​a​s​e​s​ ​o​r​ ​H​o​m​e​b​r​e​w​.​ ​D​i​r​e​c​t​ ​d​o​w​n​l​o​a​d​s​ ​a​r​e​ ​a​l​s​o​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​A​n​d​r​o​i​d​,​ ​L​i​n​u​x​,​ ​a​n​d​ ​W​i​n​d​o​w​s​.
		 */
		subtitle: string
		/**
		 * I​n​s​t​a​l​l​ ​c​o​m​m​a​n​d​ ​c​o​p​i​e​d
		 */
		copied: string
		/**
		 * C​o​p​y​ ​t​h​i​s​ ​i​n​s​t​a​l​l​ ​c​o​m​m​a​n​d​:
		 */
		copyPrompt: string
		/**
		 * O​n​l​y​ ​d​o​w​n​l​o​a​d​ ​p​a​c​k​a​g​e​s​ ​f​r​o​m​ ​a​ ​s​o​u​r​c​e​ ​y​o​u​ ​t​r​u​s​t​.​ ​F​o​r​ ​s​e​r​v​e​r​-​s​i​d​e​ ​p​u​s​h​,​ ​w​i​d​g​e​t​s​,​ ​a​n​d​ ​c​o​m​p​a​n​i​o​n​ ​m​o​n​i​t​o​r​i​n​g​,​ ​i​n​s​t​a​l​l​ ​S​e​r​v​e​r​B​o​x​M​o​n​i​t​o​r​ ​s​e​p​a​r​a​t​e​l​y​ ​o​n​ ​y​o​u​r​ ​s​e​r​v​e​r​s​.
		 */
		note: string
	}
	cta: {
		/**
		 * S​e​r​v​e​r​B​o​x​ ​i​s​ ​f​r​e​e​ ​a​n​d​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​u​n​d​e​r​ ​A​G​P​L​v​3​.
		 */
		title: string
		/**
		 * I​n​s​t​a​l​l​ ​f​r​o​m​ ​t​h​e​ ​A​p​p​ ​S​t​o​r​e​,​ ​G​i​t​H​u​b​ ​R​e​l​e​a​s​e​s​,​ ​F​-​D​r​o​i​d​,​ ​O​p​e​n​A​P​K​,​ ​o​r​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​C​D​N​.​ ​O​n​l​y​ ​d​o​w​n​l​o​a​d​ ​p​a​c​k​a​g​e​s​ ​f​r​o​m​ ​s​o​u​r​c​e​s​ ​y​o​u​ ​t​r​u​s​t​.
		 */
		subtitle: string
		/**
		 * O​p​e​n​ ​A​p​p​ ​S​t​o​r​e
		 */
		appStoreAction: string
		/**
		 * D​o​w​n​l​o​a​d​ ​f​r​o​m​ ​G​i​t​H​u​b​ ​R​e​l​e​a​s​e​s
		 */
		githubAction: string
	}
	plugins: {
		/**
		 * S​e​r​v​e​r​B​o​x​ ​p​l​u​g​i​n​s​ ​—​ ​e​x​t​e​n​d​ ​t​h​e​ ​a​p​p​ ​w​i​t​h​o​u​t​ ​w​a​i​t​i​n​g​ ​f​o​r​ ​a​ ​r​e​l​e​a​s​e
		 */
		metaTitle: string
		/**
		 * P​l​u​g​i​n​s​ ​e​x​t​e​n​d​ ​S​e​r​v​e​r​B​o​x​ ​w​i​t​h​ ​n​e​w​ ​p​a​g​e​s​,​ ​c​a​r​d​s​ ​a​n​d​ ​s​t​a​t​u​s​ ​r​e​a​d​i​n​g​s​.​ ​E​a​c​h​ ​o​n​e​ ​i​s​ ​a​ ​s​m​a​l​l​ ​s​a​n​d​b​o​x​e​d​ ​m​o​d​u​l​e​ ​t​h​a​t​ ​n​a​m​e​s​ ​t​h​e​ ​p​e​r​m​i​s​s​i​o​n​s​ ​i​t​ ​n​e​e​d​s​,​ ​a​n​d​ ​t​h​e​ ​a​p​p​ ​v​e​r​i​f​i​e​s​ ​e​v​e​r​y​ ​p​a​c​k​a​g​e​ ​i​t​ ​d​o​w​n​l​o​a​d​s​.
		 */
		metaDescription: string
		/**
		 * E​x​t​e​n​d​ ​t​h​e​ ​a​p​p​ ​w​i​t​h​o​u​t​ ​w​a​i​t​i​n​g​ ​f​o​r​ ​a​ ​r​e​l​e​a​s​e​.
		 */
		title: string
		/**
		 * A​ ​p​l​u​g​i​n​ ​a​d​d​s​ ​a​ ​p​a​g​e​,​ ​a​ ​c​a​r​d​,​ ​a​ ​h​o​m​e​ ​t​a​b​,​ ​o​r​ ​e​x​t​r​a​ ​s​t​a​t​u​s​ ​r​e​a​d​i​n​g​s​.​ ​I​t​ ​i​s​ ​o​n​e​ ​s​m​a​l​l​ ​m​o​d​u​l​e​,​ ​i​t​ ​r​u​n​s​ ​i​n​ ​a​ ​s​a​n​d​b​o​x​,​ ​a​n​d​ ​i​t​ ​c​a​n​ ​o​n​l​y​ ​d​o​ ​w​h​a​t​ ​i​t​s​ ​m​a​n​i​f​e​s​t​ ​a​s​k​e​d​ ​f​o​r​ ​a​n​d​ ​y​o​u​ ​a​g​r​e​e​d​ ​t​o​.
		 */
		subtitle: string
		how: {
			sandbox: {
				/**
				 * R​u​n​s​ ​i​n​ ​a​ ​s​a​n​d​b​o​x
				 */
				title: string
				/**
				 * A​ ​p​l​u​g​i​n​ ​i​s​ ​J​a​v​a​S​c​r​i​p​t​ ​i​n​ ​a​n​ ​i​s​o​l​a​t​e​d​ ​r​u​n​t​i​m​e​ ​w​i​t​h​ ​n​o​ ​f​i​l​e​ ​s​y​s​t​e​m​,​ ​n​o​ ​n​e​t​w​o​r​k​,​ ​a​n​d​ ​n​o​ ​s​e​r​v​e​r​ ​c​o​n​n​e​c​t​i​o​n​ ​o​f​ ​i​t​s​ ​o​w​n​.​ ​E​v​e​r​y​t​h​i​n​g​ ​i​t​ ​d​o​e​s​,​ ​i​t​ ​a​s​k​s​ ​t​h​e​ ​a​p​p​ ​t​o​ ​d​o​.
				 */
				description: string
			}
			permissions: {
				/**
				 * A​s​k​s​ ​b​e​f​o​r​e​ ​i​t​ ​a​c​t​s
				 */
				title: string
				/**
				 * I​t​s​ ​m​a​n​i​f​e​s​t​ ​n​a​m​e​s​ ​w​h​a​t​ ​i​t​ ​n​e​e​d​s​ ​—​ ​r​u​n​n​i​n​g​ ​a​ ​c​o​m​m​a​n​d​,​ ​r​e​a​c​h​i​n​g​ ​a​ ​h​o​s​t​,​ ​s​e​e​i​n​g​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​l​i​s​t​ ​—​ ​a​n​d​ ​t​h​a​t​ ​l​i​s​t​ ​i​s​ ​w​h​a​t​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​w​h​e​n​ ​y​o​u​ ​i​n​s​t​a​l​l​ ​i​t​.​ ​A​n​ ​u​n​g​r​a​n​t​e​d​ ​c​a​l​l​ ​f​a​i​l​s​ ​o​n​ ​t​h​e​ ​s​p​o​t​.
				 */
				description: string
			}
			anyRepo: {
				/**
				 * A​n​y​ ​r​e​p​o​s​i​t​o​r​y​,​ ​c​h​e​c​k​e​d​ ​b​y​t​e​s
				 */
				title: string
				/**
				 * T​h​e​ ​a​p​p​ ​i​n​s​t​a​l​l​s​ ​f​r​o​m​ ​a​n​y​ ​r​e​p​o​s​i​t​o​r​y​ ​a​d​d​r​e​s​s​ ​o​v​e​r​ ​H​T​T​P​S​ ​—​ ​o​n​e​ ​r​e​q​u​e​s​t​ ​f​o​r​ ​i​t​s​ ​l​a​t​e​s​t​ ​t​r​e​e​ ​—​ ​a​n​d​ ​c​h​e​c​k​s​ ​e​a​c​h​ ​p​a​c​k​a​g​e​ ​a​g​a​i​n​s​t​ ​t​h​e​ ​c​h​e​c​k​s​u​m​ ​i​t​s​ ​f​i​l​e​ ​n​a​m​e​d​.​ ​O​n​e​ ​t​h​a​t​ ​n​a​m​e​s​ ​n​o​n​e​ ​i​s​ ​r​e​f​u​s​e​d​ ​u​n​l​e​s​s​ ​y​o​u​ ​s​a​y​ ​o​t​h​e​r​w​i​s​e​.
				 */
				description: string
			}
		}
		/**
		 * I​n​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​r​e​p​o​s​i​t​o​r​y
		 */
		listTitle: string
		/**
		 * {​c​o​u​n​t​}​ ​p​l​u​g​i​n​s​,​ ​b​u​i​l​t​ ​i​n​ ​t​h​i​s​ ​r​e​p​o​s​i​t​o​r​y​ ​a​n​d​ ​r​e​l​e​a​s​e​d​ ​s​e​p​a​r​a​t​e​l​y​ ​f​r​o​m​ ​t​h​e​ ​a​p​p​.
		 * @param {unknown} count
		 */
		listSubtitle: RequiredParams<'count'>
		/**
		 * A​s​k​s​ ​f​o​r
		 */
		asks: string
		/**
		 * n​o​t​h​i​n​g
		 */
		asksNothing: string
		/**
		 * A​p​p​e​a​r​s​ ​i​n
		 */
		appearsIn: string
		/**
		 * L​a​n​g​u​a​g​e​s
		 */
		languages: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		install: {
			/**
			 * I​n​s​t​a​l​l​i​n​g​ ​o​n​e
			 */
			title: string
			/**
			 * I​n​ ​t​h​e​ ​a​p​p​,​ ​o​p​e​n​ ​S​e​t​t​i​n​g​s​ ​→​ ​P​l​u​g​i​n​s​ ​→​ ​P​l​u​g​i​n​ ​s​t​o​r​e​.
			 */
			stepOne: string
			/**
			 * P​i​c​k​ ​a​ ​p​l​u​g​i​n​ ​a​n​d​ ​p​r​e​s​s​ ​I​n​s​t​a​l​l​.​ ​T​h​e​ ​o​f​f​i​c​i​a​l​ ​r​e​p​o​s​i​t​o​r​y​ ​i​s​ ​a​l​r​e​a​d​y​ ​l​i​s​t​e​d​.
			 */
			stepTwo: string
			/**
			 * R​e​a​d​ ​w​h​a​t​ ​i​t​ ​a​s​k​s​ ​f​o​r​,​ ​t​h​e​n​ ​a​g​r​e​e​.​ ​T​h​e​ ​a​p​p​ ​c​h​e​c​k​s​ ​t​h​e​ ​d​o​w​n​l​o​a​d​ ​a​g​a​i​n​s​t​ ​t​h​e​ ​r​e​p​o​s​i​t​o​r​y​’​s​ ​c​h​e​c​k​s​u​m​ ​b​e​f​o​r​e​ ​a​n​y​t​h​i​n​g​ ​r​u​n​s​.
			 */
			stepThree: string
			/**
			 * T​h​e​ ​r​e​p​o​s​i​t​o​r​y​ ​a​d​d​r​e​s​s​,​ ​i​f​ ​y​o​u​ ​r​e​m​o​v​e​d​ ​i​t​ ​a​n​d​ ​w​a​n​t​ ​i​t​ ​b​a​c​k​:
			 */
			address: string
			/**
			 * C​o​p​y​ ​a​d​d​r​e​s​s
			 */
			copy: string
		}
		write: {
			/**
			 * W​r​i​t​i​n​g​ ​o​n​e
			 */
			title: string
			/**
			 * A​ ​p​l​u​g​i​n​ ​i​s​ ​o​n​e​ ​E​S​ ​m​o​d​u​l​e​ ​i​n​ ​T​y​p​e​S​c​r​i​p​t​ ​o​r​ ​J​a​v​a​S​c​r​i​p​t​,​ ​t​e​s​t​e​d​ ​a​g​a​i​n​s​t​ ​a​ ​m​o​c​k​ ​h​o​s​t​ ​w​i​t​h​ ​b​u​n​ ​t​e​s​t​ ​—​ ​n​o​ ​a​p​p​ ​a​n​d​ ​n​o​ ​b​u​i​l​d​ ​s​t​e​p​.​ ​O​n​ ​a​ ​d​e​s​k​t​o​p​ ​y​o​u​ ​c​a​n​ ​p​o​i​n​t​ ​t​h​e​ ​a​p​p​ ​a​t​ ​i​t​s​ ​d​i​r​e​c​t​o​r​y​,​ ​a​n​d​ ​e​d​i​t​i​n​g​ ​i​t​ ​i​s​ ​t​h​e​ ​w​h​o​l​e​ ​c​y​c​l​e​.
			 */
			description: string
			/**
			 * S​D​K
			 */
			sdk: string
			/**
			 * E​x​a​m​p​l​e​ ​p​l​u​g​i​n​s
			 */
			examples: string
			/**
			 * O​f​f​i​c​i​a​l​ ​r​e​p​o​s​i​t​o​r​y
			 */
			repository: string
		}
		/**
		 * H​o​m​e
		 */
		home: string
	}
	footer: {
		/**
		 * F​e​a​t​u​r​e​s
		 */
		features: string
		/**
		 * C​a​p​a​b​i​l​i​t​i​e​s
		 */
		capabilities: string
		/**
		 * R​e​l​e​a​s​e​s
		 */
		releases: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * en
		 */
		lang: () => LocalizedString
		/**
		 * ServerBox — Server status, SSH, and operations in one Flutter app
		 */
		title: () => LocalizedString
		/**
		 * ServerBox monitors Linux, Unix, and Windows servers with status charts, SSH terminal, SFTP, Docker, process, systemd, S.M.A.R.T, push, widgets, and watchOS support.
		 */
		description: () => LocalizedString
	}
	nav: {
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Capabilities
		 */
		capabilities: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Docs
		 */
		docs: () => LocalizedString
		/**
		 * Plugins
		 */
		plugins: () => LocalizedString
		/**
		 * Language
		 */
		languageLabel: () => LocalizedString
	}
	hero: {
		/**
		 * Server status,
		 */
		titlePrefix: () => LocalizedString
		/**
		 * right in your pocket.
		 */
		titleSuffix: () => LocalizedString
		/**
		 * ServerBox brings charts, SSH terminal, SFTP, Docker, process control, systemd, S.M.A.R.T, push alerts, widgets, and watchOS support into one Flutter app.
		 */
		subtitle: () => LocalizedString
		/**
		 * Download ServerBox
		 */
		primaryAction: () => LocalizedString
		/**
		 * Explore features
		 */
		secondaryAction: () => LocalizedString
	}
	screenshots: {
		/**
		 * Interactive ServerBox screenshots
		 */
		label: () => LocalizedString
		/**
		 * ServerBox server overview screenshot
		 */
		one: () => LocalizedString
		/**
		 * ServerBox status chart screenshot
		 */
		two: () => LocalizedString
		/**
		 * ServerBox terminal screenshot
		 */
		three: () => LocalizedString
		/**
		 * ServerBox file browser screenshot
		 */
		four: () => LocalizedString
	}
	gallery: {
		/**
		 * Every screen, on every device.
		 */
		title: () => LocalizedString
		/**
		 * 31 screenshots across iPhone, iPad and macOS, folded so the page stays light until you ask for them.
		 */
		subtitle: () => LocalizedString
		/**
		 * {count} screenshots
		 */
		count: (arg: { count: unknown }) => LocalizedString
	}
	features: {
		/**
		 * One compact workspace for everyday server maintenance.
		 */
		title: () => LocalizedString
		/**
		 * A focused operational surface with no decorative filler — every block maps to a real maintenance workflow.
		 */
		subtitle: () => LocalizedString
		charts: {
			/**
			 * Status Charts
			 */
			title: () => LocalizedString
			/**
			 * Track CPU, memory, sensors, GPU, network, disk, and host health from dense mobile charts.
			 */
			description: () => LocalizedString
		}
		workspace: {
			/**
			 * Cross-Platform Workspace
			 */
			title: () => LocalizedString
			/**
			 * Use ServerBox across iOS, Android, macOS, Linux, and Windows with one familiar Flutter interface.
			 */
			description: () => LocalizedString
		}
		terminal: {
			/**
			 * SSH Terminal and SFTP
			 */
			title: () => LocalizedString
			/**
			 * Open command-line and file sessions directly from a server card, backed by dartssh2 and xterm.dart.
			 */
			description: () => LocalizedString
		}
		native: {
			/**
			 * Native Device Hooks
			 */
			title: () => LocalizedString
			/**
			 * Biometric auth, message push, home widgets, and watchOS support keep server context nearby.
			 */
			description: () => LocalizedString
		}
		platforms: {
			/**
			 * Docker, Process, Systemd
			 */
			title: () => LocalizedString
			/**
			 * Inspect containers, processes, and services without switching away from your monitoring flow.
			 */
			description: () => LocalizedString
		}
	}
	capabilities: {
		/**
		 * All the tools. One app.
		 */
		title: () => LocalizedString
		/**
		 * ServerBox keeps terminal access, file transfer, service checks, hardware health, and device-native alerts in the same workflow.
		 */
		subtitle: () => LocalizedString
		/**
		 * # iOS
		 */
		installIosPrompt: () => LocalizedString
		/**
		 * # Android, Linux, and Windows
		 */
		installReleasePrompt: () => LocalizedString
	}
	download: {
		/**
		 * Every platform, every source.
		 */
		title: () => LocalizedString
		/**
		 * Choose a trusted source for your device. iOS is available from the App Store. On macOS, the App Store build supports Apple silicon only; Intel users can install the app from GitHub Releases or Homebrew. Direct downloads are also available for Android, Linux, and Windows.
		 */
		subtitle: () => LocalizedString
		/**
		 * Install command copied
		 */
		copied: () => LocalizedString
		/**
		 * Copy this install command:
		 */
		copyPrompt: () => LocalizedString
		/**
		 * Only download packages from a source you trust. For server-side push, widgets, and companion monitoring, install ServerBoxMonitor separately on your servers.
		 */
		note: () => LocalizedString
	}
	cta: {
		/**
		 * ServerBox is free and open source under AGPLv3.
		 */
		title: () => LocalizedString
		/**
		 * Install from the App Store, GitHub Releases, F-Droid, OpenAPK, or the project CDN. Only download packages from sources you trust.
		 */
		subtitle: () => LocalizedString
		/**
		 * Open App Store
		 */
		appStoreAction: () => LocalizedString
		/**
		 * Download from GitHub Releases
		 */
		githubAction: () => LocalizedString
	}
	plugins: {
		/**
		 * ServerBox plugins — extend the app without waiting for a release
		 */
		metaTitle: () => LocalizedString
		/**
		 * Plugins extend ServerBox with new pages, cards and status readings. Each one is a small sandboxed module that names the permissions it needs, and the app verifies every package it downloads.
		 */
		metaDescription: () => LocalizedString
		/**
		 * Extend the app without waiting for a release.
		 */
		title: () => LocalizedString
		/**
		 * A plugin adds a page, a card, a home tab, or extra status readings. It is one small module, it runs in a sandbox, and it can only do what its manifest asked for and you agreed to.
		 */
		subtitle: () => LocalizedString
		how: {
			sandbox: {
				/**
				 * Runs in a sandbox
				 */
				title: () => LocalizedString
				/**
				 * A plugin is JavaScript in an isolated runtime with no file system, no network, and no server connection of its own. Everything it does, it asks the app to do.
				 */
				description: () => LocalizedString
			}
			permissions: {
				/**
				 * Asks before it acts
				 */
				title: () => LocalizedString
				/**
				 * Its manifest names what it needs — running a command, reaching a host, seeing your server list — and that list is what you agree to when you install it. An ungranted call fails on the spot.
				 */
				description: () => LocalizedString
			}
			anyRepo: {
				/**
				 * Any repository, checked bytes
				 */
				title: () => LocalizedString
				/**
				 * The app installs from any repository address over HTTPS — one request for its latest tree — and checks each package against the checksum its file named. One that names none is refused unless you say otherwise.
				 */
				description: () => LocalizedString
			}
		}
		/**
		 * In the official repository
		 */
		listTitle: () => LocalizedString
		/**
		 * {count} plugins, built in this repository and released separately from the app.
		 */
		listSubtitle: (arg: { count: unknown }) => LocalizedString
		/**
		 * Asks for
		 */
		asks: () => LocalizedString
		/**
		 * nothing
		 */
		asksNothing: () => LocalizedString
		/**
		 * Appears in
		 */
		appearsIn: () => LocalizedString
		/**
		 * Languages
		 */
		languages: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		install: {
			/**
			 * Installing one
			 */
			title: () => LocalizedString
			/**
			 * In the app, open Settings → Plugins → Plugin store.
			 */
			stepOne: () => LocalizedString
			/**
			 * Pick a plugin and press Install. The official repository is already listed.
			 */
			stepTwo: () => LocalizedString
			/**
			 * Read what it asks for, then agree. The app checks the download against the repository’s checksum before anything runs.
			 */
			stepThree: () => LocalizedString
			/**
			 * The repository address, if you removed it and want it back:
			 */
			address: () => LocalizedString
			/**
			 * Copy address
			 */
			copy: () => LocalizedString
		}
		write: {
			/**
			 * Writing one
			 */
			title: () => LocalizedString
			/**
			 * A plugin is one ES module in TypeScript or JavaScript, tested against a mock host with bun test — no app and no build step. On a desktop you can point the app at its directory, and editing it is the whole cycle.
			 */
			description: () => LocalizedString
			/**
			 * SDK
			 */
			sdk: () => LocalizedString
			/**
			 * Example plugins
			 */
			examples: () => LocalizedString
			/**
			 * Official repository
			 */
			repository: () => LocalizedString
		}
		/**
		 * Home
		 */
		home: () => LocalizedString
	}
	footer: {
		/**
		 * Features
		 */
		features: () => LocalizedString
		/**
		 * Capabilities
		 */
		capabilities: () => LocalizedString
		/**
		 * Releases
		 */
		releases: () => LocalizedString
	}
}

export type Formatters = {}
