// This file is generated by ./make.dart

class BuildData {
  static const String name = "ServerBox";
  static const int build = 627;
  static const String engine = "3.13.8";
  static const String buildAt = "2023-11-01 20:01:37";
  static const int modifications = 14;
  static const int script = 25;
}
