// This file is generated by ./make.dart

class BuildData {
  static const String name = "ServerBox";
  static const int build = 724;
  static const String engine = "3.16.8";
  static const String buildAt = "2024-01-26 21:05:29";
  static const int modifications = 2;
  static const int script = 36;
}
