// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:server_box/data/model/app/tab.dart';
import 'package:server_box/data/model/server/connection_stat.dart';
import 'package:server_box/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppTabAdapter());
    registerAdapter(ConnectionResultAdapter());
    registerAdapter(ConnectionStatAdapter());
    registerAdapter(NetViewTypeAdapter());
    registerAdapter(PrivateKeyInfoAdapter());
    registerAdapter(ProxyCommandConfigAdapter());
    registerAdapter(ServerConnectionStatsAdapter());
    registerAdapter(ServerCustomAdapter());
    registerAdapter(ServerFuncBtnAdapter());
    registerAdapter(SnippetAdapter());
    registerAdapter(SpiAdapter());
    registerAdapter(SystemTypeAdapter());
    registerAdapter(VirtKeyAdapter());
    registerAdapter(WakeOnLanCfgAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppTabAdapter());
    registerAdapter(ConnectionResultAdapter());
    registerAdapter(ConnectionStatAdapter());
    registerAdapter(NetViewTypeAdapter());
    registerAdapter(PrivateKeyInfoAdapter());
    registerAdapter(ProxyCommandConfigAdapter());
    registerAdapter(ServerConnectionStatsAdapter());
    registerAdapter(ServerCustomAdapter());
    registerAdapter(ServerFuncBtnAdapter());
    registerAdapter(SnippetAdapter());
    registerAdapter(SpiAdapter());
    registerAdapter(SystemTypeAdapter());
    registerAdapter(VirtKeyAdapter());
    registerAdapter(WakeOnLanCfgAdapter());
  }
}
